import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const recipes = [
  {
    name: 'Apple Slices',
    ingredients: [{"item": "Apple", "unit": "medium", "quantity": "1"}],
    instructions: 'Wash and slice apple into wedges. Enjoy as a simple snack.',
    tags: ['aip', 'snack', 'fruit'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 95,
    protein: 0,
    carbs: 25,
    fat: 0,
    fiber: 4,
  },
  {
    name: 'Apple Slices + CocoYo',
    ingredients: [{"item": "Apple", "unit": "medium", "quantity": "1/2"}, {"item": "GT's CocoYo (plain)", "unit": "tbsp", "quantity": "1"}, {"item": "Vital Proteins Collagen Peptides", "unit": "scoop", "quantity": "1"}],
    instructions: 'Slice half a medium apple. Serve with 1 tablespoon GT\'s CocoYo coconut yogurt for dipping. Mix 1 scoop (2 tbsp) collagen peptides into water or tea on the side.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 145,
    protein: 9,
    carbs: 26,
    fat: 2,
    fiber: 4,
  },
  {
    name: 'Apple Slices with Coconut Butter',
    ingredients: [{"item": "apple", "unit": "small", "quantity": "1"}, {"item": "coconut butter", "unit": "tbsp", "quantity": "2"}],
    instructions: 'Slice apple and serve with coconut butter for dipping.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 300,
    protein: 2,
    carbs: 26,
    fat: 22,
    fiber: 5,
  },
  {
    name: 'Apple Slices with Collagen Drink',
    ingredients: [{"item": "Apple", "unit": "medium", "quantity": "1/2"}, {"item": "Water or herbal tea", "unit": "oz", "quantity": "8"}, {"item": "Vital Proteins Collagen Peptides", "unit": "scoop (10g)", "quantity": "1"}],
    instructions: '1. Slice half a medium apple into thin slices.\n\n2. Add one scoop of Vital Proteins Collagen Peptides to 8 oz of water or warm herbal tea.\n\n3. Stir until collagen is fully dissolved.\n\n4. Enjoy the apple slices alongside the collagen drink.\n\nTip: This makes a great afternoon or evening snack - the collagen supports gut healing while the apple provides fiber and natural sweetness.',
    tags: ['aip', 'snack', 'evening', 'fruit'],
    servings: 1,
    prepTime: 3,
    cookTime: null,
    calories: 80,
    protein: 9,
    carbs: 15,
    fat: 0,
    fiber: 3,
  },
  {
    name: 'Asian Ginger Chicken Lettuce Wraps',
    ingredients: [{"item": "Chicken breast", "unit": "oz", "quantity": "10"}, {"item": "Bone broth", "unit": "cup", "quantity": "1/2"}, {"item": "Butter lettuce leaves", "unit": "large leaves", "quantity": "8-10"}, {"item": "Fresh ginger, minced", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "unit": "cloves", "quantity": "2"}, {"item": "Green onion, sliced (green parts only)", "unit": "stalks", "quantity": "2"}, {"item": "Coconut aminos", "unit": "tbsp", "quantity": "3"}, {"item": "Carrots, finely diced", "unit": "cup", "quantity": "1/2"}, {"item": "Water chestnuts, diced", "unit": "cup", "quantity": "1/4"}, {"item": "Coconut oil", "unit": "tbsp", "quantity": "1"}, {"item": "Fresh cilantro, chopped", "unit": "tbsp", "quantity": "2"}, {"item": "Lime juice", "unit": "lime", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}],
    instructions: '1. Place chicken breast in Instant Pot with 1/2 cup bone broth. Cook on high pressure for 10 minutes, then natural release for 5 minutes. Shred with two forks.\n\n2. Heat coconut oil in a large skillet over medium-high heat.\n\n3. Add shredded chicken to the skillet and cook 2-3 minutes to lightly crisp the edges.\n\n4. Add minced ginger and garlic, cook 1 minute until fragrant.\n\n5. Add diced carrots and water chestnuts. Sauté 3-4 minutes until carrots soften slightly.\n\n6. Pour in coconut aminos and stir to coat everything. Cook 2 more minutes.\n\n7. Remove from heat. Stir in green onions and half the cilantro.\n\n8. Spoon mixture into butter lettuce cups.\n\n9. Top with remaining cilantro and a squeeze of fresh lime.\n\nFamily adaptation: Serve the filling over rice for family members. They can add soy sauce, sriracha, or peanut sauce. You enjoy yours in lettuce cups.\n\nMacros per serving:\n- Calories: ~680\n- Protein: 52g\n- Net Carbs: 10g\n- Fat: 28g',
    tags: ['aip', 'dinner', 'lunch', 'chicken', 'asian', 'lettuce-wraps', 'family-friendly'],
    servings: 1,
    prepTime: 10,
    cookTime: 15,
    calories: 680,
    protein: 52,
    carbs: 14,
    fat: 28,
    fiber: 4,
  },
  {
    name: 'Avocado with Olive Oil & Sea Salt',
    ingredients: [{"item": "half avocado", "unit": "medium", "quantity": "1/2"}, {"item": "extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "sea salt", "unit": "pinch", "quantity": "1"}],
    instructions: 'Slice half an avocado, drizzle with olive oil and sprinkle with sea salt.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 280,
    protein: 2,
    carbs: 9,
    fat: 28,
    fiber: 7,
  },
  {
    name: 'Bacon & Avocado Snack',
    ingredients: [{"item": "bacon (sugar-free, no nitrates)", "unit": "slices", "quantity": "3"}, {"item": "avocado", "unit": "medium", "quantity": "1/2"}],
    instructions: 'Cook bacon until crispy. Slice half an avocado and serve together.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 350,
    protein: 15,
    carbs: 9,
    fat: 30,
    fiber: 7,
  },
  {
    name: 'Bacon Wrapped Pork Chop with White Sweet Potato & Zucchini',
    ingredients: [{"item": "Boneless center-cut pork chop", "unit": "oz", "quantity": "8"}, {"item": "Sugar-free uncured bacon", "unit": "slices", "quantity": "3"}, {"item": "White sweet potato, cubed", "unit": "medium", "quantity": "1"}, {"item": "Zucchini, sliced", "unit": "medium", "quantity": "1"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried sage", "unit": "tsp", "quantity": "1/2"}, {"item": "Garlic powder", "unit": "tsp", "quantity": "1/4"}, {"item": "Dried thyme", "unit": "tsp", "quantity": "1/4"}, {"item": "Fresh lemon juice", "unit": "tbsp", "quantity": "1"}],
    instructions: '1. SEASON THE PORK CHOP: Pat the pork chop dry. Season with sea salt, sage, garlic powder, and thyme.\n\n2. WRAP WITH BACON: Lay 3 slices of bacon on a cutting board, slightly overlapping. Place the pork chop at one end and roll to wrap. Secure with toothpicks if needed.\n\n3. PREP THE SIDES: Cube the white sweet potato into 1/2-inch pieces. Slice the zucchini into 1/4-inch rounds.\n\n4. ROAST THE SWEET POTATO: Toss sweet potato cubes with half the olive oil and a pinch of salt. Roast at 400F for 15 minutes.\n\n5. SEAR THE PORK: Heat remaining olive oil in an oven-safe skillet over medium-high heat. Sear the bacon-wrapped pork chop 2-3 minutes per side until bacon is crispy.\n\n6. ADD ZUCCHINI AND FINISH: Add the zucchini to the pan around the pork chop. Transfer skillet to 400F oven and bake 12-15 minutes until pork reaches 145F internal temperature.\n\n7. REST AND SERVE: Let pork rest 5 minutes. Serve with roasted sweet potato and zucchini. Drizzle with fresh lemon juice.',
    tags: ['aip', 'dinner', 'pork', 'bacon', 'high-protein'],
    servings: 1,
    prepTime: 10,
    cookTime: 25,
    calories: 680,
    protein: 58,
    carbs: 32,
    fat: 38,
    fiber: 5,
  },
  {
    name: 'Beef Steak with Zucchini & Carrots',
    ingredients: [{"item": "Beef steak (sirloin or round)", "unit": "oz", "quantity": "8"}, {"item": "Zucchini, sliced", "unit": "medium", "quantity": "1"}, {"item": "Carrots, sliced", "unit": "medium", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Fresh rosemary", "unit": "sprig", "quantity": "1"}, {"item": "Dried thyme", "unit": "tsp", "quantity": "1/4"}],
    instructions: '1. Bring steak to room temperature (30 min). Pat dry and season generously with salt.\n\n2. Heat olive oil in cast iron skillet until smoking.\n\n3. Sear steak 3-4 minutes per side for medium-rare (adjust for preference).\n\n4. Add rosemary sprig to pan during last minute of cooking.\n\n5. Rest steak 5 minutes before slicing.\n\n6. In same pan, sauté carrots first (4-5 min) since they take longer.\n\n7. Add zucchini and cook 3-4 minutes until tender-crisp.\n\n8. Season vegetables with salt and thyme.\n\nFor grass-fed beef: Cook to medium-rare max as its leaner and can dry out.\n\nMacros per serving:\n- Calories: ~720\n- Protein: 56g\n- Net Carbs: 10g\n- Fat: 32g',
    tags: ['aip', 'dinner', 'beef', 'high-protein', 'grass-fed'],
    servings: 1,
    prepTime: 35,
    cookTime: 15,
    calories: 720,
    protein: 56,
    carbs: 14,
    fat: 32,
    fiber: 4,
  },
  {
    name: 'Berry + White Sweet Potato Smoothie',
    ingredients: [{"item": "Plain collagen peptides", "unit": "scoops", "quantity": "2"}, {"item": "Organic triple berry mix (frozen)", "unit": "cup", "quantity": "1"}, {"item": "Cooked white sweet potato (chilled)", "unit": "cup", "quantity": "1/2"}, {"item": "Fresh spinach", "unit": "cup", "quantity": "1"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Coconut oil", "unit": "tbsp", "quantity": "1"}, {"item": "Water", "unit": "cup", "quantity": "1"}, {"item": "Ice", "unit": "cup", "quantity": "1/2"}],
    instructions: '1. Add water and ice to blender first.\n\n2. Add spinach and blend briefly to break down.\n\n3. Add chilled cooked white sweet potato.\n\n4. Add frozen triple berry mix.\n\n5. Add both oils (olive oil and coconut oil).\n\n6. Add collagen peptides.\n\n7. Blend on high for 60-90 seconds until completely smooth.\n\n8. Adjust consistency with more water if needed.\n\nPrep tip: Cook sweet potatoes in bulk and keep chilled portions ready in the fridge. The resistant starch in chilled sweet potato is better for gut health.\n\nMacros per serving:\n- Calories: ~725\n- Protein: 45g (mostly from collagen)\n- Net Carbs: 32g\n- Fat: 28g',
    tags: ['aip', 'smoothie', 'high-protein', 'meal-replacement'],
    servings: 1,
    prepTime: 10,
    cookTime: null,
    calories: 470,
    protein: 23,
    carbs: 34,
    fat: 28,
    fiber: 8,
  },
  {
    name: 'Bison & Veggie Stir Fry with Avocado',
    ingredients: [{"item": "Ground bison", "unit": "lb", "quantity": "1"}, {"item": "Fresh broccoli", "unit": "cups", "notes": "cut into small florets", "quantity": "2-3"}, {"item": "Zucchini", "unit": "medium-large", "notes": "halved and sliced into half-moons", "quantity": "1"}, {"item": "Avocado", "unit": "whole", "notes": "sliced, for topping", "quantity": "1"}, {"item": "Avocado oil or coconut oil", "unit": "tbsp", "quantity": "1-2"}, {"item": "Garlic", "unit": "cloves", "notes": "minced", "quantity": "2"}, {"item": "Coconut aminos", "unit": "tbsp", "notes": "AIP-safe soy sauce substitute", "quantity": "2"}, {"item": "Sea salt", "unit": "", "quantity": "to taste"}, {"item": "Ground ginger", "unit": "tsp", "notes": "optional", "quantity": "1/2"}, {"item": "Fresh cilantro or green onion tops", "unit": "", "notes": "optional", "quantity": "for garnish"}],
    instructions: 'PREP\n====\n1. Cut broccoli into small, bite-sized florets.\n2. Halve zucchini lengthwise and slice into 1/4-inch half-moons.\n3. Mince garlic. Slice avocado (set aside for topping).\n\nCOOK THE BISON\n==============\n1. Heat 1 tbsp oil in a large skillet or wok over medium-high heat.\n2. Add ground bison and break apart with a spatula.\n3. Cook 5-7 minutes until browned and cooked through.\n4. Season with salt and optional ginger. Remove and set aside.\n\nSTIR FRY THE VEGGIES\n====================\n1. In the same skillet, add another splash of oil if needed.\n2. Add broccoli florets and cook 3-4 minutes, stirring frequently, until bright green and slightly charred but still crisp.\n3. Add zucchini and garlic. Cook another 2-3 minutes until zucchini is just tender.\n4. Season with salt.\n\nCOMBINE & FINISH\n================\n1. Return bison to the skillet with the veggies.\n2. Drizzle coconut aminos over everything and toss to coat.\n3. Cook 1 minute more to let flavors meld.\n4. Transfer to a plate and top with sliced avocado.\n5. Garnish with cilantro or green onion tops if desired.',
    tags: ['aip', 'dinner', 'bison', 'stir fry'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 830,
    protein: 82,
    carbs: 30,
    fat: 44,
    fiber: 15,
  },
  {
    name: 'Bone Broth',
    ingredients: [{"item": "Bone broth", "unit": "cup", "quantity": "1"}, {"item": "Vital Proteins Collagen Peptides", "unit": "scoop", "quantity": "1"}],
    instructions: 'Heat 1 cup bone broth until warm. Stir in 1 scoop (2 tbsp) collagen peptides until dissolved.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 75,
    protein: 19,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'Bone Broth',
    ingredients: [{"item": "Bone broth", "unit": "cup", "quantity": "1"}],
    instructions: 'Heat 1 cup bone broth until warm. Sip and enjoy.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 40,
    protein: 10,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'Cauliflower Pizza - Ground Beef',
    ingredients: [{"item": "Riced cauliflower (pre-bought bag)", "unit": "oz", "notes": "about 3 cups, thawed if frozen", "quantity": "12"}, {"item": "Tapioca starch", "unit": "tbsp", "quantity": "3"}, {"item": "Arrowroot starch", "unit": "tbsp", "quantity": "1"}, {"item": "Gelatin (unflavored)", "unit": "tbsp", "quantity": "1"}, {"item": "Olive oil (crust)", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic powder", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried oregano", "unit": "tsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Olive oil (base)", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "unit": "cloves", "quantity": "3"}, {"item": "Ground beef, 85% lean", "unit": "oz", "notes": "raw weight, pre-cooked and crumbled", "quantity": "6"}, {"item": "Fresh spinach", "unit": "cups", "notes": "packed", "quantity": "2"}, {"item": "Yellow onion, sliced", "unit": "medium", "notes": "for caramelizing", "quantity": "1"}, {"item": "Olive oil (for onions)", "unit": "tsp", "quantity": "1"}, {"item": "White mushrooms, sliced", "unit": "cup", "quantity": "1"}, {"item": "Fresh basil leaves", "unit": "leaves", "notes": "torn, added after cooking", "quantity": "5"}],
    instructions: '1. Preheat oven to 400F.\n\n2. Cook the riced cauliflower: Spread 3 cups (12 oz) pre-bought cauliflower rice in a dry skillet over medium heat. Cook for 5-6 minutes, stirring frequently, until softened and moisture is released. Transfer to a bowl and let cool for 5 minutes.\n\n3. Squeeze dry (most important step): Place cooked cauliflower rice in a clean thin kitchen towel or double layer of cheesecloth. Gather corners, twist into a tight ball, and squeeze firmly over the sink with both hands. You should extract at least 1/2 to 3/4 cup of cloudy liquid. Open the towel, break up the cauliflower, re-form the ball, and squeeze again. It should feel like dry, crumbly sand when done — any remaining moisture will make the crust soggy and impossible to hold.\n\n4. Bloom the gelatin: Sprinkle 1 tbsp unflavored gelatin evenly over 2 tbsp cold water in a small bowl (don\'t dump in a pile). Let sit undisturbed for 2-3 minutes until it forms a solid rubbery disc. Place the bowl in a small pan of simmering water for 30-60 seconds until melted into a clear liquid. Use immediately — it starts setting within a couple minutes.\n\n5. Mix the crust dough: In a large bowl, combine squeezed-dry cauliflower, 3 tbsp tapioca starch, 1 tbsp arrowroot starch, garlic powder, oregano, and sea salt. Toss with your hands to distribute evenly. Pour in the melted gelatin and 1 tbsp olive oil. Mix and knead with your hands (not a spoon) for 1-2 minutes. The dough should hold together when you squeeze a handful — like wet sand that holds its shape (sandcastle consistency). If crumbly, add 1 tsp more tapioca starch. If wet/sticky, add 1-2 tsp more tapioca starch.\n\n6. Shape the crust: Line a baking sheet with parchment paper and lightly oil the parchment. Press dough into a 10-inch circle with wet hands (re-wet frequently), about 1/4 inch thick with slightly thicker edges for a rim. Smooth any cracks with wet fingers — cracks are weak points where the crust will break. Brush the entire top with a thin layer of olive oil to help it crisp.\n\n7. Par-bake the crust: Bake at 400F on the middle rack for 15-18 minutes until dry and firm to the touch, with edges starting to turn light golden. You should be able to lift an edge with a spatula without it flopping. If the center still looks damp at 15 minutes, give it 3-5 more. Let cool on the pan for 5 minutes. Start the Ooni heating at the same time if doing pizza night. The par-baked crust can be refrigerated up to 24 hours.\n\n8. Prep toppings while the crust bakes: Cook 6 oz ground beef in a skillet over medium-high heat, breaking into small crumbles, about 5-6 minutes until browned — drain excess fat. Caramelize sliced onion in 1 tsp olive oil over medium-low heat for 15-20 minutes, stirring every few minutes, until deep golden and sweet. Wilt 2 cups spinach in a hot pan for 30-60 seconds, then press dry with paper towel. Sauté sliced mushrooms over medium-high heat for 3-4 minutes until golden (don\'t crowd the pan).\n\n9. Make the garlic oil base: Warm 1 tbsp olive oil with 3 minced garlic cloves in a small pan over low heat for 1-2 minutes until fragrant and barely golden — NOT brown. Remove from heat immediately.\n\n10. Assemble the pizza: Spread garlic oil over the par-baked crust, leaving a 1/2 inch border. Layer bottom to top: wilted spinach (acts as moisture barrier), ground beef crumbles, caramelized onions, mushroom slices. Keep everything in a single even layer — don\'t overload.\n\n11. Cook in the Ooni: Slide assembled pizza (on parchment) onto the Ooni peel. Cook at 750-800F for 2-3 minutes, rotating 90 degrees every 30-45 seconds with the turning peel. Pull parchment out after 30 seconds once crust sets on the stone. Watch edges closely — cauliflower crust chars faster than regular dough. If it burns before toppings heat, lower to 600-650F and cook 4-5 minutes instead.\n\n12. Finish and serve: Slide onto a cutting board, scatter torn fresh basil leaves on top, and let rest 1-2 minutes for the crust to firm up. Cut with a sharp chef\'s knife or pizza rocker (a rolling pizza cutter may drag the toppings).\n\nTroubleshooting: Crust is soggy/falls apart = not enough moisture squeezed out in step 3. Crust crumbles when lifting a slice = gelatin wasn\'t fully dissolved or dough needed more kneading. Burns in Ooni before toppings heat = lower to 600-650F and cook longer. Crust sticks to parchment = use more oil on parchment or let crust cool fully before moving.',
    tags: ['aip', 'dinner', 'pizza', 'beef', 'ooni'],
    servings: 1,
    prepTime: 25,
    cookTime: 25,
    calories: 954,
    protein: 50.9,
    carbs: 64.3,
    fat: 58.9,
    fiber: 11.4,
  },
  {
    name: 'Cauliflower Pizza - Shredded Chicken',
    ingredients: [{"item": "Riced cauliflower (pre-bought bag)", "unit": "oz", "notes": "about 3 cups, thawed if frozen", "quantity": "12"}, {"item": "Tapioca starch", "unit": "tbsp", "quantity": "3"}, {"item": "Arrowroot starch", "unit": "tbsp", "quantity": "1"}, {"item": "Gelatin (unflavored)", "unit": "tbsp", "quantity": "1"}, {"item": "Olive oil (crust)", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic powder", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried oregano", "unit": "tsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Olive oil (base)", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "unit": "cloves", "quantity": "3"}, {"item": "Chicken breast, cooked and shredded", "unit": "oz", "notes": "cooked weight", "quantity": "6"}, {"item": "Fresh spinach", "unit": "cups", "notes": "packed", "quantity": "2"}, {"item": "Yellow onion, sliced", "unit": "medium", "notes": "for caramelizing", "quantity": "1"}, {"item": "Olive oil (for onions)", "unit": "tsp", "quantity": "1"}, {"item": "White mushrooms, sliced", "unit": "cup", "quantity": "1"}, {"item": "Fresh basil leaves", "unit": "leaves", "notes": "torn, added after cooking", "quantity": "5"}],
    instructions: '1. Preheat oven to 400F.\n\n2. Cook the riced cauliflower: Spread 3 cups (12 oz) pre-bought cauliflower rice in a dry skillet over medium heat. Cook for 5-6 minutes, stirring frequently, until softened and moisture is released. Transfer to a bowl and let cool for 5 minutes.\n\n3. Squeeze dry (most important step): Place cooked cauliflower rice in a clean thin kitchen towel or double layer of cheesecloth. Gather corners, twist into a tight ball, and squeeze firmly over the sink with both hands. You should extract at least 1/2 to 3/4 cup of cloudy liquid. Open the towel, break up the cauliflower, re-form the ball, and squeeze again. It should feel like dry, crumbly sand when done — any remaining moisture will make the crust soggy and impossible to hold.\n\n4. Bloom the gelatin: Sprinkle 1 tbsp unflavored gelatin evenly over 2 tbsp cold water in a small bowl (don\'t dump in a pile). Let sit undisturbed for 2-3 minutes until it forms a solid rubbery disc. Place the bowl in a small pan of simmering water for 30-60 seconds until melted into a clear liquid. Use immediately — it starts setting within a couple minutes.\n\n5. Mix the crust dough: In a large bowl, combine squeezed-dry cauliflower, 3 tbsp tapioca starch, 1 tbsp arrowroot starch, garlic powder, oregano, and sea salt. Toss with your hands to distribute evenly. Pour in the melted gelatin and 1 tbsp olive oil. Mix and knead with your hands (not a spoon) for 1-2 minutes. The dough should hold together when you squeeze a handful — like wet sand that holds its shape (sandcastle consistency). If crumbly, add 1 tsp more tapioca starch. If wet/sticky, add 1-2 tsp more tapioca starch.\n\n6. Shape the crust: Line a baking sheet with parchment paper and lightly oil the parchment. Press dough into a 10-inch circle with wet hands (re-wet frequently), about 1/4 inch thick with slightly thicker edges for a rim. Smooth any cracks with wet fingers — cracks are weak points where the crust will break. Brush the entire top with a thin layer of olive oil to help it crisp.\n\n7. Par-bake the crust: Bake at 400F on the middle rack for 15-18 minutes until dry and firm to the touch, with edges starting to turn light golden. You should be able to lift an edge with a spatula without it flopping. If the center still looks damp at 15 minutes, give it 3-5 more. Let cool on the pan for 5 minutes. Start the Ooni heating at the same time if doing pizza night. The par-baked crust can be refrigerated up to 24 hours.\n\n8. Prep toppings while the crust bakes: Use 6 oz pre-cooked chicken breast — shred with two forks into bite-sized pieces and season with a pinch of sea salt and a squeeze of lemon if desired. If cold, warm briefly in a pan. Caramelize sliced onion in 1 tsp olive oil over medium-low heat for 15-20 minutes, stirring every few minutes, until deep golden and sweet. Wilt 2 cups spinach in a hot pan for 30-60 seconds, then press dry with paper towel. Sauté sliced mushrooms over medium-high heat for 3-4 minutes until golden (don\'t crowd the pan).\n\n9. Make the garlic oil base: Warm 1 tbsp olive oil with 3 minced garlic cloves in a small pan over low heat for 1-2 minutes until fragrant and barely golden — NOT brown. Remove from heat immediately.\n\n10. Assemble the pizza: Spread garlic oil over the par-baked crust, leaving a 1/2 inch border. Layer bottom to top: wilted spinach (acts as moisture barrier), shredded chicken, caramelized onions, mushroom slices. Keep everything in a single even layer — don\'t overload.\n\n11. Cook in the Ooni: Slide assembled pizza (on parchment) onto the Ooni peel. Cook at 750-800F for 2-3 minutes, rotating 90 degrees every 30-45 seconds with the turning peel. Pull parchment out after 30 seconds once crust sets on the stone. Watch edges closely — cauliflower crust chars faster than regular dough. If it burns before toppings heat, lower to 600-650F and cook 4-5 minutes instead.\n\n12. Finish and serve: Slide onto a cutting board, scatter torn fresh basil leaves on top, and let rest 1-2 minutes for the crust to firm up. Cut with a sharp chef\'s knife or pizza rocker (a rolling pizza cutter may drag the toppings).\n\nTroubleshooting: Crust is soggy/falls apart = not enough moisture squeezed out in step 3. Crust crumbles when lifting a slice = gelatin wasn\'t fully dissolved or dough needed more kneading. Burns in Ooni before toppings heat = lower to 600-650F and cook longer. Crust sticks to parchment = use more oil on parchment or let crust cool fully before moving.',
    tags: ['aip', 'dinner', 'pizza', 'chicken', 'ooni'],
    servings: 1,
    prepTime: 25,
    cookTime: 25,
    calories: 873,
    protein: 71.6,
    carbs: 64.3,
    fat: 40.3,
    fiber: 11.4,
  },
  {
    name: 'Chicken Breast with Veggie Medley',
    ingredients: [{"item": "Chicken breast", "unit": "oz", "notes": "3/4 lb", "quantity": "12"}, {"item": "Birds Eye Steamfresh Broccoli, Cauliflower & Carrots", "unit": "bag (10.8 oz)", "quantity": "1"}, {"item": "Salt", "unit": "", "quantity": "to taste"}, {"item": "Olive oil or avocado oil", "unit": "tbsp", "notes": "for cooking", "quantity": "1"}],
    instructions: 'CHICKEN\\n=======\\n1. Season chicken breast with salt (and any AIP-safe seasonings).\\n2. Heat oil in a skillet over medium-high heat.\\n3. Cook chicken 6-7 minutes per side until internal temp reaches 165°F.\\n4. Let rest 5 minutes, then slice.\\n\\nVEGGIE MEDLEY\\n=============\\n1. Cook the entire bag of Birds Eye Steamfresh Broccoli, Cauliflower & Carrots on the stovetop: add to a pot with a splash of water, cover, and steam for about 11 minutes until tender.\\n2. Season with salt and a drizzle of oil if desired.',
    tags: ['aip', 'dinner', 'chicken'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 495,
    protein: 78,
    carbs: 20,
    fat: 12,
    fiber: 8,
  },
  {
    name: 'Chicken Taco Salad with Avocado-Lime Dressing',
    ingredients: [{"item": "Chicken thighs (boneless, skinless)", "unit": "oz", "quantity": "8"}, {"item": "Romaine lettuce, chopped", "unit": "cups", "quantity": "3-4"}, {"item": "Avocado", "unit": "medium", "quantity": "1"}, {"item": "Red onion, diced", "unit": "tbsp", "quantity": "2"}, {"item": "Fresh cilantro, chopped", "unit": "tbsp", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "3"}, {"item": "Lime", "unit": "lime", "quantity": "1"}, {"item": "Garlic clove, minced", "unit": "clove", "quantity": "1"}, {"item": "Dried oregano", "unit": "tsp", "quantity": "1"}, {"item": "Garlic powder", "unit": "tsp", "quantity": "1/2"}, {"item": "Onion powder", "unit": "tsp", "quantity": "1/2"}, {"item": "Turmeric", "unit": "tsp", "quantity": "1/4"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}],
    instructions: '1. Make the dressing: In a small bowl or blender, combine 1 full avocado, 2 tbsp olive oil, juice of 1 lime, minced garlic, and a pinch of salt. Blend or mash until smooth. Set aside.\n\n2. Season the chicken: Mix oregano, garlic powder, onion powder, turmeric, and salt.\n\n3. Cook the chicken: Heat 1 tbsp olive oil in a skillet over medium-high heat. Cook chicken thighs 5-6 minutes per side until cooked through. Let rest 2 minutes, then slice or shred.\n\n4. Build the salad: Arrange romaine lettuce on a plate or in a bowl.\n\n5. Top with sliced or shredded chicken while still warm.\n\n6. Add diced red onion and fresh cilantro.\n\n7. Drizzle generously with avocado-lime dressing.\n\nFamily adaptation: Serve the seasoned chicken separately so family members can build tacos with shells, cheese, sour cream, and tomato salsa.',
    tags: ['aip', 'dinner', 'lunch', 'chicken', 'dairy-free', 'gluten-free', 'taco-tuesday'],
    servings: 1,
    prepTime: 10,
    cookTime: 12,
    calories: 900,
    protein: 50,
    carbs: 22,
    fat: 71,
    fiber: 12,
  },
  {
    name: 'Chicken Thighs with Sweet Potato & Spinach',
    ingredients: [{"item": "Boneless chicken thighs", "unit": "oz", "quantity": "12"}, {"item": "White sweet potato", "unit": "cup cubed", "quantity": "1"}, {"item": "Fresh spinach", "unit": "cups", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried thyme", "unit": "tsp", "quantity": "1/2"}, {"item": "Fresh sage leaves", "unit": "leaves", "quantity": "3-4"}],
    instructions: '1. Preheat oven to 425°F.\n\n2. Pat chicken thighs dry. Season with salt and thyme.\n\n3. Toss sweet potato cubes with half the olive oil and salt.\n\n4. Place chicken and sweet potatoes on sheet pan.\n\n5. Roast 35-40 minutes until chicken reaches 175°F and sweet potatoes are tender.\n\n6. In a small pan, wilt spinach with remaining olive oil and sage.\n\n7. Serve chicken over sweet potatoes with spinach on the side.\n\nThe chicken thighs provide extra fat which helps with satiety.\n\nMacros per serving:\n- Calories: ~700\n- Protein: 48g\n- Net Carbs: 18g\n- Fat: 28g',
    tags: ['aip', 'dinner', 'chicken', 'high-protein', 'sheet-pan'],
    servings: 1,
    prepTime: 10,
    cookTime: 40,
    calories: 644,
    protein: 64,
    carbs: 29,
    fat: 32,
    fiber: 5,
  },
  {
    name: 'Coconut Curry Chicken',
    ingredients: [{"item": "Chicken thighs, boneless", "unit": "oz", "quantity": "10"}, {"item": "Full-fat coconut milk", "unit": "cup", "quantity": "1/2"}, {"item": "Cauliflower florets", "unit": "cup", "quantity": "1"}, {"item": "Carrots, sliced", "unit": "cup", "quantity": "1/2"}, {"item": "Fresh ginger, minced", "unit": "tbsp", "quantity": "1"}, {"item": "Turmeric powder", "unit": "tsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "unit": "cloves", "quantity": "2"}, {"item": "Onion powder", "unit": "tsp", "quantity": "1/2"}, {"item": "Coconut oil", "unit": "tbsp", "quantity": "1"}, {"item": "Fresh cilantro, chopped", "unit": "tbsp", "quantity": "2"}, {"item": "Lime juice", "unit": "lime", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1"}, {"item": "Fresh spinach", "unit": "cup", "quantity": "1"}],
    instructions: '1. Cut chicken thighs into bite-sized pieces. Season with turmeric, onion powder, and 1/2 tsp salt.\n\n2. Heat coconut oil in a large skillet or wok over medium-high heat.\n\n3. Add chicken and cook 4-5 minutes until browned. Remove and set aside.\n\n4. In the same pan, sauté ginger and garlic for 1 minute until fragrant.\n\n5. Add carrots and cauliflower. Cook 3-4 minutes.\n\n6. Pour in coconut milk and remaining salt. Stir and bring to a simmer.\n\n7. Return chicken to pan. Simmer 10-12 minutes until vegetables are tender and sauce thickens slightly.\n\n8. Stir in spinach until wilted. Remove from heat.\n\n9. Top with fresh cilantro and a squeeze of lime.\n\nNote: This is an AIP-safe "curry" using turmeric and ginger instead of traditional curry powder (which contains nightshades and seeds).\n\nFamily adaptation: Serve over jasmine rice for the family. They can add traditional curry paste or powder to their portions.\n\nMacros per serving:\n- Calories: ~750\n- Protein: 50g\n- Net Carbs: 12g\n- Fat: 45g',
    tags: ['aip', 'dinner', 'lunch', 'chicken', 'curry', 'coconut', 'family-friendly'],
    servings: 1,
    prepTime: 10,
    cookTime: 25,
    calories: 750,
    protein: 50,
    carbs: 16,
    fat: 45,
    fiber: 4,
  },
  {
    name: 'Coconut Yogurt + Fresh Berries',
    ingredients: [{"item": "GT's CocoYo (plain)", "unit": "cup", "quantity": "1/2"}, {"item": "Fresh strawberries, raspberries & blackberries", "unit": "cup", "quantity": "1/2"}, {"item": "Vital Proteins Collagen Peptides", "unit": "scoop", "quantity": "1"}],
    instructions: 'Combine 1/2 cup GT\'s CocoYo plain coconut yogurt with 1/2 cup fresh berries (strawberries, raspberries, blackberries). Mix 1 scoop (2 tbsp) collagen peptides into water or tea on the side.\n\nBerry notes: Stick to strawberries, raspberries, and blackberries for lower sugar. Blueberries are AIP-safe but higher in sugar - use sparingly or as an occasional swap.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 205,
    protein: 11,
    carbs: 17,
    fat: 11,
    fiber: 3,
  },
  {
    name: 'Coconut Yogurt with Coconut Butter',
    ingredients: [{"item": "coconut yogurt (unsweetened)", "unit": "cup", "quantity": "1/2"}, {"item": "coconut butter", "unit": "tbsp", "quantity": "1"}],
    instructions: 'Stir coconut butter into coconut yogurt.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 250,
    protein: 2,
    carbs: 12,
    fat: 22,
    fiber: 3,
  },
  {
    name: 'Collagen Bone Broth',
    ingredients: [{"item": "Bone broth", "unit": "cup", "quantity": "1"}, {"item": "Vital Proteins Collagen Peptides", "unit": "scoop (10g)", "quantity": "1"}],
    instructions: '1. Heat 8-12 oz of bone broth in a small pot until warm (not boiling).\n\n2. Pour warm broth into a mug.\n\n3. Add one scoop of Vital Proteins Collagen Peptides.\n\n4. Stir until collagen is fully dissolved.\n\n5. Enjoy warm.\n\nTip: This is perfect as an afternoon snack - the collagen and bone broth both support gut healing and provide protein without breaking ketosis significantly.',
    tags: ['aip', 'snack', 'gut-healing', 'high-protein', 'quick'],
    servings: 1,
    prepTime: 3,
    cookTime: null,
    calories: 80,
    protein: 19,
    carbs: 3,
    fat: 1,
    fiber: 0,
  },
  {
    name: 'Diced Strawberries',
    ingredients: [{"item": "Strawberries (fresh)", "unit": "cup, diced", "quantity": "1"}],
    instructions: '1. Wash strawberries thoroughly under cool running water.\n\n2. Remove stems and hull.\n\n3. Dice into bite-sized pieces.\n\nNote: 1 cup diced is approximately 166g (~8-10 medium strawberries).',
    tags: ['aip', 'snack', 'fruit', 'simple'],
    servings: 1,
    prepTime: 3,
    cookTime: null,
    calories: 53,
    protein: 1.1,
    carbs: 12.7,
    fat: 0.5,
    fiber: 3.3,
  },
  {
    name: 'Fresh Berries',
    ingredients: [{"item": "Fresh strawberries, raspberries & blackberries", "unit": "cup", "quantity": "1/2"}, {"item": "Vital Proteins Collagen Peptides", "unit": "scoop", "quantity": "1"}],
    instructions: 'Wash and prepare 1/2 cup fresh berries (strawberries, raspberries, blackberries). Mix 1 scoop (2 tbsp) collagen peptides into water or tea on the side.\n\nBerry notes: Stick to strawberries, raspberries, and blackberries for lower sugar. Blueberries are AIP-safe but higher in sugar - use sparingly or as an occasional swap.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 105,
    protein: 11,
    carbs: 10,
    fat: 1,
    fiber: 3,
  },
  {
    name: 'Garlic Ginger Beef & Broccoli Bowl',
    ingredients: [{"item": "Ground beef (grass-fed 85% lean)", "unit": "oz", "quantity": "8"}, {"item": "Broccoli florets", "unit": "cups", "quantity": "2"}, {"item": "Cauliflower rice", "unit": "cup", "quantity": "1"}, {"item": "Coconut aminos", "unit": "tbsp", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Fresh ginger, minced", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "quantity": "3"}, {"item": "Apple cider vinegar", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}],
    instructions: 'Heat olive oil in a large skillet over medium-high heat. Add minced ginger and garlic, saute 30 seconds until fragrant. Add ground beef, break up and cook until browned, 5-6 minutes. Add broccoli florets and coconut aminos, stir to combine. Cover and cook 3-4 minutes until broccoli is tender-crisp. Add apple cider vinegar and salt, toss to coat. Serve over warmed cauliflower rice.\n\nFamily adaptation: Serve over regular rice for the family, add soy sauce on the side.',
    tags: ['aip', 'dinner', 'lunch', 'beef', 'dairy-free', 'gluten-free'],
    servings: 1,
    prepTime: 10,
    cookTime: 12,
    calories: 720,
    protein: 49,
    carbs: 25,
    fat: 45,
    fiber: 7,
  },
  {
    name: 'Garlic Ginger Beef & Broccoli Bowl',
    ingredients: [{"item": "Ground beef (grass-fed 85% lean)", "unit": "oz", "quantity": "8"}, {"item": "Broccoli florets", "unit": "cups", "quantity": "2"}, {"item": "Cauliflower rice", "unit": "cup", "quantity": "1"}, {"item": "Coconut aminos", "unit": "tbsp", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Fresh ginger, minced", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "quantity": "3"}, {"item": "Apple cider vinegar", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}],
    instructions: '1. Heat olive oil in a large skillet over medium-high heat.\n\n2. Add minced ginger and garlic, sauté 30 seconds until fragrant.\n\n3. Add ground beef, break up and cook until browned, 5-6 minutes.\n\n4. Add broccoli florets and coconut aminos, stir to combine.\n\n5. Cover and cook 3-4 minutes until broccoli is tender-crisp.\n\n6. Add apple cider vinegar and salt, toss to coat.\n\n7. Serve over warmed cauliflower rice.\n\nFamily adaptation: Serve over regular rice for the family, add soy sauce on the side. Can also serve with noodles.',
    tags: ['aip', 'dinner', 'lunch', 'beef', 'dairy-free', 'gluten-free'],
    servings: 1,
    prepTime: 10,
    cookTime: 12,
    calories: 720,
    protein: 49,
    carbs: 25,
    fat: 45,
    fiber: 7,
  },
  {
    name: 'Garlic Ginger Beef & Broccoli Bowl',
    ingredients: [{"item": "Ground beef (grass-fed 85% lean)", "unit": "oz", "quantity": "8"}, {"item": "Broccoli florets", "unit": "cups", "quantity": "2"}, {"item": "Cauliflower rice", "unit": "cup", "quantity": "1"}, {"item": "Coconut aminos", "unit": "tbsp", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Fresh ginger, minced", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "quantity": "3"}, {"item": "Apple cider vinegar", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}],
    instructions: 'Heat olive oil in a large skillet over medium-high heat. Add minced ginger and garlic, saute 30 seconds until fragrant. Add ground beef, break up and cook until browned, 5-6 minutes. Add broccoli florets and coconut aminos, stir to combine. Cover and cook 3-4 minutes until broccoli is tender-crisp. Add apple cider vinegar and salt, toss to coat. Serve over warmed cauliflower rice.\n\nFamily adaptation: Serve over regular rice for the family, add soy sauce on the side.',
    tags: ['aip', 'dinner', 'lunch', 'beef', 'dairy-free', 'gluten-free'],
    servings: 1,
    prepTime: 10,
    cookTime: 12,
    calories: 720,
    protein: 49,
    carbs: 25,
    fat: 45,
    fiber: 7,
  },
  {
    name: 'Ginger Chicken Thighs with Bok Choy',
    ingredients: [{"item": "Boneless skinless chicken thighs", "unit": "oz", "quantity": "8"}, {"item": "Baby bok choy, halved lengthwise", "unit": "heads", "quantity": "2"}, {"item": "Coconut aminos", "unit": "tbsp", "quantity": "2"}, {"item": "Fresh ginger, grated", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "quantity": "3"}, {"item": "Honey", "unit": "tsp", "quantity": "1"}, {"item": "Lime juice", "unit": "tbsp", "quantity": "1"}, {"item": "Avocado oil", "unit": "tbsp", "quantity": "2"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Fresh cilantro", "unit": "tbsp", "notes": "chopped, for garnish", "quantity": "2"}],
    instructions: '1. Pat chicken thighs dry with paper towels and season both sides with sea salt.\n\n2. Make the glaze: In a small bowl, whisk together coconut aminos, grated ginger, minced garlic, honey, and lime juice. Set aside.\n\n3. Heat 1 tbsp avocado oil in a large skillet over medium-high heat. Place chicken thighs presentation-side down and cook undisturbed for 5-6 minutes until golden and crispy. Flip and cook another 4-5 minutes until cooked through (165F internal). Remove to a plate and let rest.\n\n4. In the same skillet, add remaining 1 tbsp avocado oil. Place bok choy halves cut-side down and cook 2-3 minutes until nicely charred. Flip and cook 1-2 more minutes until tender-crisp.\n\n5. Pour the glaze into the skillet around the bok choy and let it bubble and reduce for 1-2 minutes until slightly thickened and glossy. Roll the bok choy in the glaze to coat.\n\n6. Slice the rested chicken thighs and serve over the glazed bok choy. Spoon any remaining pan glaze over everything and garnish with fresh cilantro.\n\nFamily adaptation: Serve over steamed rice or noodles for the rest of the family.',
    tags: ['aip', 'dinner', 'lunch', 'chicken', 'asian', 'coconut-aminos', 'family-friendly'],
    servings: 1,
    prepTime: 10,
    cookTime: 20,
    calories: 680,
    protein: 52,
    carbs: 18,
    fat: 38,
    fiber: 3,
  },
  {
    name: 'Ground Beef with Zucchini & Green Beans',
    ingredients: [{"item": "Ground beef (85% lean)", "unit": "oz", "quantity": "8"}, {"item": "Zucchini, diced", "unit": "medium", "quantity": "1"}, {"item": "Green beans", "unit": "cup", "quantity": "1"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried oregano", "unit": "tsp", "quantity": "1/2"}, {"item": "Fresh parsley, chopped", "unit": "tbsp", "quantity": "2"}],
    instructions: '1. Heat olive oil in a large skillet over medium-high heat.\n\n2. Add ground beef, breaking it up as it cooks.\n\n3. Season with salt and oregano.\n\n4. Cook until browned, about 6-8 minutes.\n\n5. Push beef to one side, add green beans to empty side.\n\n6. Cook green beans 4-5 minutes, stirring occasionally.\n\n7. Add zucchini and mix everything together.\n\n8. Cook another 3-4 minutes until zucchini is tender.\n\n9. Garnish with fresh parsley.\n\nGreat for meal prep - doubles well and reheats nicely.\n\nMacros per serving:\n- Calories: ~680\n- Protein: 48g\n- Net Carbs: 8g\n- Fat: 32g',
    tags: ['aip', 'dinner', 'beef', 'high-protein', 'one-pan', 'quick'],
    servings: 1,
    prepTime: 5,
    cookTime: 20,
    calories: 680,
    protein: 48,
    carbs: 12,
    fat: 32,
    fiber: 4,
  },
  {
    name: 'Ground Turkey Patties with Cauliflower Rice & Broccoli',
    ingredients: [{"item": "Ground turkey (93% lean)", "unit": "oz", "quantity": "9"}, {"item": "Cauliflower rice", "unit": "cup", "quantity": "1"}, {"item": "Broccoli florets", "unit": "cup", "quantity": "1"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried oregano", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried basil", "unit": "tsp", "quantity": "1/4"}],
    instructions: '1. Mix ground turkey with salt, oregano, and basil. Form into 2 patties.\n\n2. Heat half the olive oil in a skillet over medium-high heat.\n\n3. Cook patties 5-6 minutes per side until internal temp reaches 165°F.\n\n4. Remove patties and set aside.\n\n5. Add remaining oil to pan. Add cauliflower rice and broccoli.\n\n6. Sauté 6-8 minutes until vegetables are tender.\n\n7. Season vegetables with salt and serve with patties.\n\nMake extra patties for tomorrows lunch (leftover).\n\nMacros per serving:\n- Calories: ~680\n- Protein: 54g\n- Net Carbs: 10g\n- Fat: 24g',
    tags: ['aip', 'dinner', 'turkey', 'high-protein', 'meal-prep'],
    servings: 1,
    prepTime: 10,
    cookTime: 20,
    calories: 680,
    protein: 54,
    carbs: 15,
    fat: 24,
    fiber: 5,
  },
  {
    name: 'Half Avocado',
    ingredients: [{"item": "Avocado", "unit": "medium", "quantity": "1/2"}],
    instructions: 'Slice avocado in half, remove pit, and enjoy.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
  },
  {
    name: 'Herb-Crusted Pork Chops with Roasted Vegetables',
    ingredients: [{"item": "Bone-in pork chops (wild hog or regular)", "unit": "oz", "quantity": "10"}, {"item": "Butternut squash, cubed", "unit": "cup", "quantity": "1"}, {"item": "Brussels sprouts, halved", "unit": "cup", "quantity": "1"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "2"}, {"item": "Fresh rosemary, chopped", "unit": "tbsp", "quantity": "1"}, {"item": "Fresh thyme leaves", "unit": "tsp", "quantity": "1"}, {"item": "Fresh sage, chopped", "unit": "tsp", "quantity": "1"}, {"item": "Garlic powder", "unit": "tsp", "quantity": "1/2"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1"}, {"item": "Apple cider vinegar", "unit": "tbsp", "quantity": "1"}],
    instructions: '1. Preheat oven to 400°F.\n\n2. Toss butternut squash and Brussels sprouts with 1 tbsp olive oil and 1/2 tsp salt. Spread on a sheet pan.\n\n3. Roast vegetables for 15 minutes to get a head start.\n\n4. Mix rosemary, thyme, sage, garlic powder, and remaining salt. Pat pork chops dry and coat with herb mixture.\n\n5. Heat remaining 1 tbsp olive oil in an oven-safe skillet. Sear chops 3 minutes per side.\n\n6. Add skillet to oven alongside vegetables. Roast 10-15 minutes until pork reaches 145°F.\n\n7. Rest pork 5 minutes. Drizzle vegetables with apple cider vinegar before serving.\n\nNote: If using wild hog chops, they are leaner - don\'t overcook! Check at 140°F internal and let carryover cooking bring to 145°F.\n\nFamily adaptation: Serve with mashed potatoes or rice for the family. The herb-crusted pork is delicious for everyone.\n\nMacros per serving:\n- Calories: ~700\n- Protein: 48g\n- Net Carbs: 18g\n- Fat: 32g',
    tags: ['aip', 'dinner', 'pork', 'wild-game', 'sheet-pan', 'family-friendly'],
    servings: 1,
    prepTime: 15,
    cookTime: 30,
    calories: 700,
    protein: 48,
    carbs: 24,
    fat: 32,
    fiber: 6,
  },
  {
    name: 'Honey Garlic Chicken Party Wings',
    ingredients: [{"item": "Chicken party wings (flats and drumettes)", "unit": "lb", "quantity": "1"}, {"item": "Honey", "unit": "tsp", "quantity": "2"}, {"item": "Garlic cloves, minced", "quantity": "4"}, {"item": "Coconut aminos", "unit": "tbsp", "quantity": "1"}, {"item": "Fresh ginger, grated", "unit": "tsp", "quantity": "1"}, {"item": "Avocado oil", "unit": "tbsp", "quantity": "1.5"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Broccoli florets", "unit": "cups", "quantity": "2"}, {"item": "Fresh cilantro", "unit": "tbsp", "notes": "chopped, for garnish", "quantity": "1"}],
    instructions: '1. Preheat oven to 425F and line a baking sheet with parchment paper.\n\n2. Pat wings dry thoroughly with paper towels — this is key for crispy skin. Toss with 1/2 tbsp avocado oil and sea salt. Arrange in a single layer on the baking sheet with space between each piece.\n\n3. Roast for 25 minutes, then flip each wing and roast another 15-20 minutes until the skin is golden and crispy and juices run clear.\n\n4. While the wings roast, make the glaze: In a small saucepan over low heat, combine honey, minced garlic, coconut aminos, grated ginger, and remaining 1 tbsp avocado oil. Stir for 2-3 minutes until fragrant and warmed through. Remove from heat.\n\n5. During the last 10 minutes of wing roasting, toss broccoli florets with a drizzle of avocado oil and a pinch of salt on a separate baking sheet (or on the same sheet if there\'s room). Roast until tender and lightly charred.\n\n6. Pull the wings from the oven and immediately toss in a large bowl with the honey garlic glaze until evenly coated.\n\n7. Serve the glazed wings alongside the roasted broccoli, garnished with fresh cilantro.\n\nFamily adaptation: These are already kid-friendly as-is. Serve with sweet potato fries or rice on the side for the family.',
    tags: ['aip', 'dinner', 'lunch', 'chicken', 'honey-garlic', 'wings', 'family-friendly', 'kid-friendly'],
    servings: 1,
    prepTime: 10,
    cookTime: 45,
    calories: 700,
    protein: 52,
    carbs: 21,
    fat: 43,
    fiber: 3,
  },
  {
    name: 'Honey Garlic Chicken with Roasted Root Vegetables',
    ingredients: [{"item": "Chicken breast", "unit": "oz", "quantity": "10"}, {"item": "Parsnips, cubed", "unit": "cup", "quantity": "1/2"}, {"item": "Carrots, cubed", "unit": "cup", "quantity": "1/2"}, {"item": "Turnips, cubed", "unit": "cup", "quantity": "1/2"}, {"item": "Raw honey", "unit": "tbsp", "quantity": "1"}, {"item": "Coconut aminos", "unit": "tbsp", "quantity": "2"}, {"item": "Garlic cloves, minced", "unit": "cloves", "quantity": "3"}, {"item": "Fresh ginger, minced", "unit": "tsp", "quantity": "1"}, {"item": "Avocado oil", "unit": "tbsp", "quantity": "2"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Fresh thyme", "unit": "sprigs", "quantity": "3-4"}, {"item": "Green onion, sliced", "unit": "tbsp", "quantity": "2"}],
    instructions: '1. Preheat oven to 400°F.\n\n2. Toss root vegetables (parsnips, carrots, turnips) with 1 tbsp avocado oil and salt. Spread on sheet pan with thyme sprigs.\n\n3. Roast vegetables for 15 minutes.\n\n4. Meanwhile, make the glaze: Whisk honey, coconut aminos, garlic, and ginger together.\n\n5. Slice chicken breast into thick strips or medallions. Season with salt.\n\n6. Heat remaining 1 tbsp avocado oil in an oven-safe skillet. Sear chicken 2 minutes per side.\n\n7. Pour honey garlic glaze over chicken. Transfer skillet to oven alongside vegetables.\n\n8. Roast 12-15 minutes until chicken reaches 165°F and glaze is sticky.\n\n9. Serve chicken over roasted vegetables. Garnish with green onions.\n\nFamily adaptation: This is delicious as-is for the whole family! They can add rice on the side. The honey garlic flavor is universally loved.\n\nMacros per serving:\n- Calories: ~680\n- Protein: 52g\n- Net Carbs: 22g\n- Fat: 28g',
    tags: ['aip', 'dinner', 'chicken', 'honey-garlic', 'sheet-pan', 'family-friendly', 'kid-friendly'],
    servings: 1,
    prepTime: 15,
    cookTime: 30,
    calories: 680,
    protein: 52,
    carbs: 28,
    fat: 28,
    fiber: 6,
  },
  {
    name: 'Italian Herb Ground Beef Bowl',
    ingredients: [{"item": "Ground beef (grass-fed 85% lean)", "unit": "oz", "quantity": "8"}, {"item": "Spaghetti squash, cooked", "unit": "cups", "quantity": "1.5"}, {"item": "Zucchini, diced", "unit": "medium", "quantity": "1"}, {"item": "Fresh basil, chopped", "unit": "tbsp", "quantity": "3"}, {"item": "Fresh oregano, chopped", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "unit": "cloves", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "2"}, {"item": "Bone broth", "unit": "cup", "quantity": "1/4"}, {"item": "Nutritional yeast (if tolerated)", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried Italian herbs", "unit": "tsp", "quantity": "1"}],
    instructions: '1. If you don\'t have pre-cooked spaghetti squash: Halve squash, remove seeds, brush with olive oil, and roast at 400°F for 40 minutes. Scrape out strands.\n\n2. Heat 1 tbsp olive oil in a skillet over medium-high heat.\n\n3. Add ground beef, breaking it up as it cooks. Season with Italian herbs and salt.\n\n4. When beef is almost done, add garlic and zucchini. Cook 3-4 minutes.\n\n5. Add bone broth and simmer 2-3 minutes to reduce slightly.\n\n6. Serve beef mixture over spaghetti squash.\n\n7. Drizzle with remaining olive oil. Top with fresh basil, oregano, and nutritional yeast.\n\nNote: Skip nutritional yeast if you\'re in strict elimination phase - it\'s a reintroduction food for some.\n\nFamily adaptation: Serve their portion over regular pasta with marinara sauce and Parmesan cheese. The seasoned beef works great either way.\n\nMacros per serving:\n- Calories: ~720\n- Protein: 48g\n- Net Carbs: 10g\n- Fat: 42g',
    tags: ['aip', 'dinner', 'lunch', 'beef', 'italian', 'pasta-alternative', 'family-friendly'],
    servings: 1,
    prepTime: 10,
    cookTime: 20,
    calories: 720,
    protein: 48,
    carbs: 15,
    fat: 42,
    fiber: 5,
  },
  {
    name: 'Korean-Style Beef Bowl',
    ingredients: [{"item": "Flank steak, thinly sliced against the grain", "unit": "oz", "quantity": "8"}, {"item": "Coconut aminos", "unit": "tbsp", "quantity": "2"}, {"item": "Fresh ginger, grated", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "quantity": "3"}, {"item": "Honey", "unit": "tsp", "quantity": "1"}, {"item": "Avocado oil", "unit": "tbsp", "quantity": "2"}, {"item": "Zucchini, half-moon sliced", "unit": "medium", "quantity": "1"}, {"item": "Carrots, matchstick cut", "unit": "cup", "quantity": "1/2"}, {"item": "Riced cauliflower (pre-bought bag)", "unit": "cup", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Fresh cilantro", "unit": "tbsp", "notes": "chopped, for garnish", "quantity": "2"}],
    instructions: '1. Make the marinade: Whisk together coconut aminos, grated ginger, minced garlic, and honey in a bowl. Add the thinly sliced flank steak, toss to coat, and let sit for at least 10 minutes (or up to 30 minutes).\n\n2. Heat 1 tbsp avocado oil in a large skillet or wok over high heat until just starting to smoke. Remove the steak from the marinade (reserve the marinade) and spread in a single layer. Sear without stirring for 2 minutes until browned, then flip and cook 1 more minute. Remove to a plate.\n\n3. In the same skillet, add remaining 1 tbsp avocado oil. Add carrots and cook 2 minutes, then add zucchini slices and cook another 2-3 minutes until just tender with some color. Season with a pinch of salt.\n\n4. Cook the cauliflower rice: In a separate skillet over medium heat, cook 1 cup pre-bought cauliflower rice in a dry pan for 4-5 minutes, stirring occasionally, until heated through and slightly dried out. Season with a pinch of salt.\n\n5. Pour the reserved marinade into the vegetable skillet and let it bubble for 30 seconds. Return the seared beef to the pan and toss everything together for 30 seconds to coat.\n\n6. Serve the beef and vegetables over the cauliflower rice, garnished with fresh cilantro.\n\nFamily adaptation: Serve over steamed white rice or noodles for the family instead of cauliflower rice.',
    tags: ['aip', 'dinner', 'lunch', 'beef', 'korean', 'coconut-aminos', 'asian', 'family-friendly'],
    servings: 1,
    prepTime: 15,
    cookTime: 15,
    calories: 720,
    protein: 50,
    carbs: 19,
    fat: 42,
    fiber: 4,
  },
  {
    name: 'Lemon Rosemary Turkey Meatballs with Roasted Root Vegetables',
    ingredients: [{"item": "Ground turkey (93% lean)", "unit": "oz", "quantity": "8"}, {"item": "Arrowroot starch", "unit": "tbsp", "quantity": "1"}, {"item": "Sweet potato, cubed", "unit": "medium", "quantity": "1/2"}, {"item": "Carrots, chopped", "unit": "medium", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "2"}, {"item": "Lemon (juice + zest)", "unit": "lemon", "quantity": "1"}, {"item": "Fresh rosemary, chopped", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic cloves, minced", "quantity": "2"}, {"item": "Dried thyme", "unit": "tsp", "quantity": "1/2"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1"}],
    instructions: '1. Preheat oven to 400F.\n\n2. Make the meatballs: In a bowl, combine ground turkey, arrowroot starch, lemon zest, half the minced garlic, chopped rosemary, thyme, and 1/2 tsp salt. Mix gently and form into 8-10 meatballs.\n\n3. Prep the vegetables: Toss cubed sweet potato and chopped carrots with 1 tbsp olive oil, remaining garlic, and 1/2 tsp salt on a sheet pan.\n\n4. Roast vegetables for 10 minutes, then add meatballs to the pan. Drizzle meatballs with remaining 1 tbsp olive oil.\n\n5. Roast another 18-20 minutes until meatballs are cooked through and vegetables are golden and tender.\n\n6. Squeeze fresh lemon juice over everything before serving.\n\nFamily adaptation: Serve meatballs with pasta or in sub rolls for the family. Add marinara sauce on the side.',
    tags: ['aip', 'dinner', 'lunch', 'turkey', 'dairy-free', 'gluten-free'],
    servings: 1,
    prepTime: 15,
    cookTime: 30,
    calories: 735,
    protein: 48,
    carbs: 37,
    fat: 43,
    fiber: 6,
  },
  {
    name: 'Mediterranean Herb Chicken Bowl',
    ingredients: [{"item": "Chicken breast", "unit": "oz", "quantity": "10"}, {"item": "Cucumber, diced", "unit": "cup", "quantity": "1"}, {"item": "Kalamata olives (pitted)", "unit": "olives", "quantity": "10"}, {"item": "Red onion, thinly sliced", "unit": "tbsp", "quantity": "2"}, {"item": "Fresh parsley, chopped", "unit": "tbsp", "quantity": "3"}, {"item": "Fresh mint, chopped", "unit": "tbsp", "quantity": "1"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "2"}, {"item": "Lemon juice", "unit": "lemon", "quantity": "1"}, {"item": "Dried oregano", "unit": "tsp", "quantity": "1"}, {"item": "Garlic powder", "unit": "tsp", "quantity": "1/2"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Romaine lettuce, chopped", "unit": "cups", "quantity": "2"}, {"item": "Avocado", "unit": "medium", "quantity": "1/2"}],
    instructions: '1. Season chicken breast with oregano, garlic powder, and salt.\n\n2. Heat 1 tbsp olive oil in a skillet over medium-high heat.\n\n3. Cook chicken 6-7 minutes per side until internal temp reaches 165°F.\n\n4. Let chicken rest 5 minutes, then slice.\n\n5. Make the dressing: Whisk remaining 1 tbsp olive oil with lemon juice, a pinch of salt, and dried oregano.\n\n6. In a large bowl, combine romaine lettuce, cucumber, olives, red onion, parsley, and mint.\n\n7. Top with sliced chicken and avocado.\n\n8. Drizzle with lemon-olive oil dressing.\n\nFamily adaptation: Serve with pita bread, hummus, and feta cheese for the family. Add tzatziki sauce for them. Your bowl stays AIP-clean.\n\nMacros per serving:\n- Calories: ~720\n- Protein: 55g\n- Net Carbs: 8g\n- Fat: 48g',
    tags: ['aip', 'dinner', 'lunch', 'chicken', 'mediterranean', 'salad', 'family-friendly'],
    servings: 1,
    prepTime: 10,
    cookTime: 15,
    calories: 720,
    protein: 55,
    carbs: 14,
    fat: 48,
    fiber: 6,
  },
  {
    name: 'Morning Coffee',
    ingredients: [{"item": "Black coffee", "unit": "oz", "quantity": "12"}, {"item": "MCT oil", "unit": "tbsp", "quantity": "1"}, {"item": "Laird Superfood mushroom powder", "unit": "scoop", "quantity": "1"}],
    instructions: '1. Brew fresh black coffee (12 oz).\n\n2. Add 1 tbsp MCT oil.\n\n3. Add 1 scoop Laird Superfood mushroom powder.\n\n4. Blend or froth until well combined and slightly creamy.\n\n5. Serve immediately.\n\nNote: This is technically breaking your fast but provides clean energy. The MCT oil provides sustained energy without spiking blood sugar.',
    tags: ['aip', 'breakfast', 'coffee', 'keto-friendly', 'quick'],
    servings: 1,
    prepTime: 5,
    cookTime: null,
    calories: 130,
    protein: 0,
    carbs: 3,
    fat: 15,
    fiber: 1,
  },
  {
    name: 'Morning Coffee with MCT',
    ingredients: [{"item": "Coffee", "unit": "oz", "quantity": "12"}, {"item": "MCT oil", "unit": "tbsp", "quantity": "1"}],
    instructions: '1. Brew 12 oz of fresh black coffee.\n\n2. Add 1 tbsp MCT oil while coffee is still hot.\n\n3. Blend or froth vigorously until well combined and slightly creamy.\n\n4. Serve immediately.\n\nNote: Blending helps emulsify the MCT oil so it does not separate. A milk frother or immersion blender works well.',
    tags: ['aip', 'snack', 'evening', 'high-protein', 'quick', 'calming'],
    servings: 1,
    prepTime: 2,
    cookTime: null,
    calories: 60,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    name: 'Olives in Olive Oil',
    ingredients: [{"item": "Divina Organic Pitted Green Olives", "quantity": "4"}, {"item": "Divina Kalamata Olives (pitted)", "quantity": "4"}, {"item": "Extra virgin olive oil", "unit": "tsp", "quantity": "1"}],
    instructions: 'Place 4 green olives and 4 kalamata olives in a small bowl. Drizzle with about 1 tsp extra virgin olive oil. Using Divina Organic Pitted Green Olives and Divina Kalamata Olives.',
    tags: ['aip', 'snack'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 112,
    protein: 0,
    carbs: 2,
    fat: 12,
    fiber: 1,
  },
  {
    name: 'Pork Tenderloin with Broccoli & Cauliflower',
    ingredients: [{"item": "Pork tenderloin", "unit": "oz", "quantity": "8"}, {"item": "Broccoli florets", "unit": "cup", "quantity": "1"}, {"item": "Cauliflower florets", "unit": "cup", "quantity": "1"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried rosemary", "unit": "tsp", "quantity": "1/2"}, {"item": "Garlic powder (if tolerated)", "unit": "tsp", "quantity": "1/4"}],
    instructions: '1. Preheat oven to 400°F.\n\n2. Pat pork tenderloin dry. Season with salt, rosemary, and garlic powder.\n\n3. Heat olive oil in oven-safe skillet. Sear pork on all sides (2 min per side).\n\n4. Toss broccoli and cauliflower with a drizzle of oil and salt.\n\n5. Add vegetables around the pork in the pan.\n\n6. Transfer to oven and roast 15-20 minutes until pork reaches 145°F.\n\n7. Rest pork 5 minutes before slicing.\n\nPork tenderloin is very lean - use a meat thermometer to avoid overcooking.\n\nMacros per serving:\n- Calories: ~680\n- Protein: 52g\n- Net Carbs: 9g\n- Fat: 24g',
    tags: ['aip', 'dinner', 'pork', 'high-protein', 'sheet-pan'],
    servings: 1,
    prepTime: 10,
    cookTime: 25,
    calories: 680,
    protein: 52,
    carbs: 14,
    fat: 24,
    fiber: 5,
  },
  {
    name: 'Roasted Chicken Breast with Sweet Potato & Zucchini',
    ingredients: [{"item": "Chicken breast", "unit": "oz", "quantity": "10"}, {"item": "White sweet potato", "unit": "cup cubed", "quantity": "1/2"}, {"item": "Zucchini, sliced", "unit": "medium", "quantity": "1"}, {"item": "Fresh spinach", "unit": "cup", "quantity": "1"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried basil", "unit": "tsp", "quantity": "1/2"}],
    instructions: '1. Preheat oven to 400°F.\n\n2. Toss sweet potato cubes with half the olive oil and salt.\n\n3. Roast sweet potatoes for 15 minutes.\n\n4. Season chicken breast with salt and basil.\n\n5. Add chicken and zucchini to the pan with sweet potatoes.\n\n6. Drizzle remaining oil over chicken and zucchini.\n\n7. Roast another 20-25 minutes until chicken reaches 165°F.\n\n8. Serve over fresh spinach (the heat will wilt it slightly).\n\nMacros per serving:\n- Calories: ~720\n- Protein: 54g\n- Net Carbs: 19g\n- Fat: 24g',
    tags: ['aip', 'dinner', 'chicken', 'high-protein', 'sheet-pan'],
    servings: 1,
    prepTime: 10,
    cookTime: 40,
    calories: 750,
    protein: 60,
    carbs: 24,
    fat: 25,
    fiber: 5,
  },
  {
    name: 'Sautéed Chicken Breast with Green Beans & Spinach',
    ingredients: [{"item": "Chicken breast", "unit": "oz", "quantity": "10"}, {"item": "Green beans (fresh or frozen)", "unit": "cup", "quantity": "1"}, {"item": "Fresh spinach", "unit": "cups", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "to taste", "quantity": ""}, {"item": "Dried thyme", "unit": "tsp", "quantity": "1/2"}, {"item": "Garlic powder (if tolerated)", "unit": "tsp", "quantity": "1/4"}],
    instructions: '1. Pat chicken breast dry and season with salt, thyme, and garlic powder.\n\n2. Heat olive oil in a skillet over medium-high heat.\n\n3. Cook chicken breast 6-7 minutes per side until internal temp reaches 165°F.\n\n4. Remove chicken and let rest 5 minutes.\n\n5. In the same pan, add green beans and sauté 5-6 minutes until tender-crisp.\n\n6. Add spinach and toss until just wilted (1-2 minutes).\n\n7. Slice chicken and serve over vegetables.\n\nHotLogic Meal Prep: Place raw seasoned chicken and green beans in HotLogic container. Cook for 2-3 hours. Add fresh spinach before serving to wilt.\n\nMacros per serving:\n- Calories: ~650\n- Protein: 52g\n- Net Carbs: 8g\n- Fat: 22g',
    tags: ['aip', 'dinner', 'lunch', 'chicken', 'high-protein', 'hotlogic'],
    servings: 1,
    prepTime: 10,
    cookTime: 20,
    calories: 745,
    protein: 69,
    carbs: 12,
    fat: 24,
    fiber: 4,
  },
  {
    name: 'Shredded Pork Taco Bowl',
    ingredients: [{"item": "Pork shoulder (bone-in or boneless)", "unit": "lbs", "notes": "for a batch \u2014 yields about 4 servings", "quantity": "2"}, {"item": "Sea salt", "unit": "tbsp", "quantity": "1"}, {"item": "Garlic powder", "unit": "tsp", "quantity": "1"}, {"item": "Dried oregano", "unit": "tsp", "quantity": "1"}, {"item": "Onion powder", "unit": "tsp", "quantity": "1"}, {"item": "Avocado oil", "unit": "tbsp", "quantity": "2"}, {"item": "Lime juice", "unit": "tbsp", "notes": "for the pork", "quantity": "2"}, {"item": "Romaine lettuce, shredded", "unit": "cups", "notes": "per serving", "quantity": "2"}, {"item": "Avocado, sliced", "unit": "medium", "notes": "per serving", "quantity": "1/2"}, {"item": "Red onion, thinly sliced", "unit": "tbsp", "notes": "quick-pickled, per serving", "quantity": "2"}, {"item": "Fresh cilantro, chopped", "unit": "tbsp", "notes": "per serving", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "notes": "for dressing, per serving", "quantity": "1"}, {"item": "Lime", "unit": "wedge", "notes": "for serving", "quantity": "1"}],
    instructions: '1. Pat the pork shoulder dry and rub all over with sea salt, garlic powder, oregano, and onion powder.\n\n2. Heat avocado oil in a skillet over medium-high heat on the stovetop. Sear the pork on all sides, about 3-4 minutes per side, until deeply browned. This step is optional but adds a lot of flavor.\n\n3. Place the seared pork in the crockpot. Add lime juice, cover, and cook on low for 8 hours or high for 4 hours until the pork is fork-tender and shreds easily.\n\n4. While the pork cooks, quick-pickle the red onion: place thinly sliced red onion in a small bowl with 2 tbsp lime juice and a pinch of salt. Let sit at least 30 minutes, stirring occasionally. Refrigerate until ready to use.\n\n5. Shred the pork with two forks directly in the crockpot, mixing the shredded meat with the juices.\n\n6. Build the bowl: Start with shredded romaine, top with about 6 oz of the shredded pork, sliced avocado, pickled red onion, and fresh cilantro. Drizzle with olive oil and a squeeze of fresh lime.\n\nFamily adaptation: Serve the shredded pork in tortillas or on slider buns with coleslaw for the family. Leftover pork keeps well for 4-5 days refrigerated.',
    tags: ['aip', 'dinner', 'lunch', 'pork', 'taco-tuesday', 'dairy-free', 'gluten-free', 'batch-cook'],
    servings: 1,
    prepTime: 15,
    cookTime: 195,
    calories: 750,
    protein: 48,
    carbs: 12,
    fat: 52,
    fiber: 5,
  },
  {
    name: 'Smash Burgers with Caramelized Onions & Avocado',
    ingredients: [{"item": "Ground beef, 85% lean", "unit": "oz", "notes": "formed into two 4oz balls", "quantity": "8"}, {"item": "Avocado, sliced", "unit": "medium", "quantity": "1/2"}, {"item": "Yellow onion, sliced", "unit": "medium", "notes": "for caramelizing", "quantity": "1/2"}, {"item": "Butter lettuce leaves", "unit": "leaves", "notes": "for wrapping", "quantity": "4"}, {"item": "Avocado oil", "unit": "tsp", "notes": "for onions", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Garlic powder", "unit": "tsp", "quantity": "1/4"}, {"item": "Broccoli florets", "unit": "cups", "notes": "for roasted side", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tsp", "notes": "for broccoli", "quantity": "1"}],
    instructions: '1. Caramelize the onions first since they take the longest: Heat 1 tsp avocado oil in a skillet over medium-low heat. Add sliced onion with a pinch of salt and cook 15-20 minutes, stirring every few minutes, until deep golden and sweet. Set aside.\n\n2. Preheat oven to 425F. Toss broccoli florets with 1 tsp olive oil and a pinch of salt on a baking sheet. Roast for 15-18 minutes until tender and lightly charred at the edges.\n\n3. While the broccoli roasts, make the smash burgers: Heat a cast iron skillet over high heat until smoking hot. Form the ground beef into two loose 4 oz balls — do not pack tightly.\n\n4. Place the beef balls on the screaming hot skillet and immediately smash flat with a sturdy spatula or burger press, pressing hard to about 1/4 inch thick. Season the top with sea salt and garlic powder.\n\n5. Cook without moving for 3 minutes until a deep brown crust forms and the edges are crispy. Flip and cook 2 more minutes. The rendered beef fat is all the oil you need — no added oil for the patties.\n\n6. Assemble: Stack each patty in butter lettuce leaves and top with caramelized onions and sliced avocado. Serve alongside the roasted broccoli.\n\nFamily adaptation: Serve the patties on regular buns with your family\'s favorite toppings. Add cheese for non-AIP eaters.',
    tags: ['aip', 'dinner', 'lunch', 'beef', 'burgers', 'family-friendly', 'kid-friendly', 'cast-iron'],
    servings: 1,
    prepTime: 10,
    cookTime: 25,
    calories: 770,
    protein: 46,
    carbs: 16,
    fat: 54,
    fiber: 5,
  },
  {
    name: 'Sweet Potato & Ground Bison Hash',
    ingredients: [{"item": "Sweet potato", "unit": "large", "notes": "about 1 cup diced", "quantity": "1/2"}, {"item": "Ground bison", "unit": "oz", "quantity": "8"}, {"item": "Chopped spinach or kale", "unit": "cups", "quantity": "1-2"}, {"item": "Diced onion", "unit": "tbsp", "quantity": "2"}, {"item": "Garlic", "unit": "clove", "notes": "minced", "quantity": "1"}, {"item": "Avocado oil or coconut oil", "unit": "tbsp", "quantity": "1-2"}, {"item": "Avocado", "unit": "", "notes": "optional but great for calories", "quantity": "1/4-1/2"}, {"item": "Sea salt", "unit": "", "quantity": "to taste"}, {"item": "Dried thyme, rosemary, or fresh parsley", "unit": "", "notes": "optional", "quantity": "to taste"}],
    instructions: 'COOK THE SWEET POTATOES\n=======================\n1. Heat 1 tbsp oil in a skillet over medium heat.\n2. Add diced sweet potatoes and a pinch of salt.\n3. Cook 8-10 minutes, stirring occasionally, until softened and slightly crispy.\n4. If needed, add 1-2 tbsp water and cover briefly to steam.\n\nBROWN THE MEAT\n==============\n1. Push potatoes to one side. Add ground bison and garlic.\n2. Cook until browned and fully cooked through (5-7 minutes).\n3. Season with salt and herbs.\n\nADD GREENS\n==========\n1. Stir in spinach/kale and cook 1-2 minutes until wilted.\n\nFINISH\n======\n1. Drizzle extra oil if needed for more calories.\n2. Top with sliced avocado.',
    tags: ['aip', 'dinner', 'hash', 'bison'],
    servings: 1,
    prepTime: null,
    cookTime: null,
    calories: 620,
    protein: 42,
    carbs: 35,
    fat: 34,
    fiber: 8,
  },
  {
    name: 'Taco Salad with Avocado-Lime Dressing',
    ingredients: [{"item": "Ground beef (grass-fed 85% lean)", "unit": "oz", "quantity": "8"}, {"item": "Romaine lettuce, chopped", "unit": "cups", "quantity": "3-4"}, {"item": "Avocado", "unit": "medium", "quantity": "1"}, {"item": "Red onion, diced", "unit": "tbsp", "quantity": "2"}, {"item": "Fresh cilantro, chopped", "unit": "tbsp", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "3"}, {"item": "Lime juice", "unit": "lime", "quantity": "1"}, {"item": "Garlic clove, minced", "unit": "clove", "quantity": "1"}, {"item": "Dried oregano", "unit": "tsp", "quantity": "1"}, {"item": "Garlic powder", "unit": "tsp", "quantity": "1/2"}, {"item": "Onion powder", "unit": "tsp", "quantity": "1/2"}, {"item": "Turmeric", "unit": "tsp", "quantity": "1/4"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}],
    instructions: '1. Make the dressing: In a small bowl or blender, combine 1 full avocado, 2 tbsp olive oil, juice of 1 lime, minced garlic, and a pinch of salt. Blend or mash until smooth. Set aside.\n\n2. Season the beef: Mix oregano, garlic powder, onion powder, turmeric, and salt in a small bowl.\n\n3. Cook the beef: Heat 1 tbsp olive oil in a skillet over medium-high heat. Add ground beef and break it up as it cooks.\n\n4. Add the seasoning mix to the beef and stir to combine. Cook until browned and cooked through, about 6-8 minutes.\n\n5. Build the salad: Arrange romaine lettuce on a plate or in a bowl.\n\n6. Top with the seasoned ground beef while still warm.\n\n7. Add diced red onion and fresh cilantro.\n\n8. Drizzle generously with avocado-lime dressing.\n\nFamily adaptation: Serve the seasoned beef separately so family members can build tacos with shells, cheese, sour cream, and tomato salsa while you enjoy your AIP salad version.',
    tags: ['aip', 'dinner', 'lunch', 'salad', 'beef', 'dairy-free', 'gluten-free'],
    servings: 1,
    prepTime: 10,
    cookTime: 10,
    calories: 930,
    protein: 49,
    carbs: 18,
    fat: 77,
    fiber: 10,
  },
  {
    name: 'Turkey Breast with Carrots & Spinach',
    ingredients: [{"item": "Turkey breast cutlets", "unit": "oz", "quantity": "9"}, {"item": "Carrots, sliced", "unit": "medium", "quantity": "2"}, {"item": "Fresh spinach", "unit": "cups", "quantity": "2"}, {"item": "Extra virgin olive oil", "unit": "tbsp", "quantity": "1"}, {"item": "Sea salt", "unit": "tsp", "quantity": "1/2"}, {"item": "Dried sage", "unit": "tsp", "quantity": "1/2"}, {"item": "Fresh lemon juice", "unit": "tbsp", "quantity": "1"}],
    instructions: '1. Pound turkey cutlets to even thickness. Season with salt and sage.\n\n2. Heat olive oil in a skillet over medium-high heat.\n\n3. Cook turkey 4-5 minutes per side until internal temp reaches 165°F.\n\n4. Remove turkey and set aside.\n\n5. Add carrots to pan with a splash of water. Cover and steam 5-6 minutes.\n\n6. Uncover, add spinach, and toss until wilted.\n\n7. Drizzle lemon juice over vegetables.\n\n8. Slice turkey and serve over vegetables.\n\nTurkey breast is very lean - do not overcook or it will dry out.\n\nMacros per serving:\n- Calories: ~650\n- Protein: 54g\n- Net Carbs: 10g\n- Fat: 18g',
    tags: ['aip', 'dinner', 'turkey', 'high-protein', 'lean'],
    servings: 1,
    prepTime: 10,
    cookTime: 15,
    calories: 650,
    protein: 54,
    carbs: 14,
    fat: 18,
    fiber: 4,
  },
  {
    name: 'Vanilla Coconut Collagen Ice Cream',
    ingredients: [{"item": "Full-fat coconut milk", "unit": "can (13.5 oz)", "quantity": "1"}, {"item": "Collagen peptides", "unit": "scoops", "quantity": "2"}, {"item": "Raw honey", "unit": "tbsp", "quantity": "2"}, {"item": "Pure vanilla extract (alcohol-free)", "unit": "tsp", "quantity": "1"}, {"item": "Sea salt", "unit": "pinch", "quantity": "1"}],
    instructions: '1. BLEND THE BASE: Add coconut milk, collagen peptides, honey, vanilla, and sea salt to a blender. Blend on high for 30 seconds until collagen is fully dissolved and mixture is smooth.\n\n2. FILL THE PINT: Pour the mixture into a Ninja Creami pint container. It should come to the max fill line (add a splash of water if needed to reach the line).\n\n3. FREEZE: Place the lid on the container and freeze for at least 24 hours (must be solid frozen).\n\n4. PROCESS: Remove the pint from the freezer. Place in the Ninja Creami and run the ICE CREAM cycle.\n\n5. CHECK TEXTURE: If still too icy after the first spin, create a hole in the center, and run the RE-SPIN cycle once more.\n\n6. SERVE: Scoop and enjoy immediately for soft-serve texture, or return to freezer for 15-20 minutes for firmer scoops.\n\nTIPS:\n- For berry swirl: fold in 2 tbsp mashed mixed berries after processing.\n- For extra creaminess, use coconut cream instead of coconut milk.\n- The collagen adds protein without affecting flavor or texture.\n- Make sure the base is FULLY frozen (24 hrs minimum) before processing.',
    tags: ['aip', 'dessert', 'ninja-creami'],
    servings: 2,
    prepTime: 5,
    cookTime: null,
    calories: 385,
    protein: 12,
    carbs: 21,
    fat: 29,
    fiber: 0,
  },
];

async function main() {
  console.log('Seeding AIP recipes...');
  let created = 0;
  let skipped = 0;

  for (const recipe of recipes) {
    const existing = await prisma.recipe.findFirst({ where: { name: recipe.name } });
    if (existing) {
      console.log(`  Skipped (exists): ${recipe.name}`);
      skipped++;
      continue;
    }
    await prisma.recipe.create({ data: recipe });
    console.log(`  Created: ${recipe.name}`);
    created++;
  }

  console.log(`\nDone! Created ${created} recipes, skipped ${skipped} existing.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
