import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// AIP Food Database
// Nutritional data is per 100g serving unless otherwise noted
// Sources: USDA FoodData Central, AIP protocol guidelines

const foods = [
  // ── MEAT: POULTRY ──
  {
    name: 'Chicken Breast',
    category: 'MEAT_POULTRY',
    aipPhase: 'ELIMINATION',
    calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true, preferPasture: true,
    richInB12: true, richInSelenium: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Chicken Thighs',
    category: 'MEAT_POULTRY',
    aipPhase: 'ELIMINATION',
    calories: 209, protein: 26, carbs: 0, fat: 10.9, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true, preferPasture: true,
    richInB12: true, richInIron: true, richInZinc: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Ground Chicken',
    category: 'MEAT_POULTRY',
    aipPhase: 'ELIMINATION',
    calories: 172, protein: 21, carbs: 0, fat: 9.3, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true, preferPasture: true,
    richInB12: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Ground Turkey',
    category: 'MEAT_POULTRY',
    aipPhase: 'ELIMINATION',
    calories: 170, protein: 21, carbs: 0, fat: 9.4, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true, preferPasture: true,
    richInB12: true, richInSelenium: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Turkey Breast',
    category: 'MEAT_POULTRY',
    aipPhase: 'ELIMINATION',
    calories: 135, protein: 30, carbs: 0, fat: 1, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true, preferPasture: true,
    richInB12: true, richInSelenium: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Duck Breast',
    category: 'MEAT_POULTRY',
    aipPhase: 'ELIMINATION',
    calories: 201, protein: 23.5, carbs: 0, fat: 11.2, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true, preferPasture: true,
    richInB12: true, richInIron: true, richInSelenium: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },

  // ── MEAT: BEEF ──
  {
    name: 'Ground Beef (85/15)',
    category: 'MEAT_BEEF',
    aipPhase: 'ELIMINATION',
    calories: 215, protein: 26, carbs: 0, fat: 11.5, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferGrassFed: true, preferOrganic: true,
    richInB12: true, richInIron: true, richInZinc: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Ground Beef (90/10)',
    category: 'MEAT_BEEF',
    aipPhase: 'ELIMINATION',
    calories: 176, protein: 26, carbs: 0, fat: 7.5, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferGrassFed: true, preferOrganic: true,
    richInB12: true, richInIron: true, richInZinc: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Beef Steak (Sirloin)',
    category: 'MEAT_BEEF',
    aipPhase: 'ELIMINATION',
    calories: 206, protein: 26, carbs: 0, fat: 10.6, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferGrassFed: true,
    richInB12: true, richInIron: true, richInZinc: true, richInSelenium: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Beef Roast (Chuck)',
    category: 'MEAT_BEEF',
    aipPhase: 'ELIMINATION',
    calories: 250, protein: 26, carbs: 0, fat: 16, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferGrassFed: true,
    richInB12: true, richInIron: true, richInZinc: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Beef Liver',
    category: 'MEAT_BEEF',
    aipPhase: 'ELIMINATION',
    calories: 135, protein: 20.4, carbs: 3.9, fat: 3.6, fiber: 0, netCarbs: 3.9,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferGrassFed: true, preferOrganic: true,
    richInB12: true, richInIron: true, richInZinc: true, richInFolate: true, richInCholine: true, richInSelenium: true,
    servingSize: '3 oz', servingSizeGrams: 85,
  },
  {
    name: 'Bison (Ground)',
    category: 'MEAT_BEEF',
    aipPhase: 'ELIMINATION',
    calories: 146, protein: 20, carbs: 0, fat: 7, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferGrassFed: true,
    richInB12: true, richInIron: true, richInZinc: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },

  // ── MEAT: PORK ──
  {
    name: 'Pork Tenderloin',
    category: 'MEAT_PORK',
    aipPhase: 'ELIMINATION',
    calories: 143, protein: 26, carbs: 0, fat: 3.5, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferPasture: true,
    richInB12: true, richInSelenium: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Pork Chops',
    category: 'MEAT_PORK',
    aipPhase: 'ELIMINATION',
    calories: 196, protein: 25, carbs: 0, fat: 10, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferPasture: true,
    richInB12: true, richInSelenium: true, richInZinc: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Bacon (Uncured, Sugar-Free)',
    category: 'MEAT_PORK',
    aipPhase: 'ELIMINATION',
    calories: 541, protein: 37, carbs: 1.4, fat: 42, fiber: 0, netCarbs: 1.4,
    tyramineLevel: 'MODERATE', histamineLevel: 'MODERATE',
    preferPasture: true, preferOrganic: true,
    richInB12: true, richInSelenium: true,
    servingSize: '2 slices', servingSizeGrams: 28,
  },

  // ── SEAFOOD ──
  {
    name: 'Salmon (Wild)',
    category: 'SEAFOOD',
    aipPhase: 'ELIMINATION',
    calories: 208, protein: 20, carbs: 0, fat: 13, fiber: 0, netCarbs: 0,
    tyramineLevel: 'MODERATE', histamineLevel: 'MODERATE',
    preferWildCaught: true,
    richInB12: true, richInOmega3: true, richInVitaminD: true, richInSelenium: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Cod',
    category: 'SEAFOOD',
    aipPhase: 'ELIMINATION',
    calories: 82, protein: 18, carbs: 0, fat: 0.7, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferWildCaught: true,
    richInB12: true, richInSelenium: true, richInIodine: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Mahi-Mahi',
    category: 'SEAFOOD',
    aipPhase: 'ELIMINATION',
    calories: 85, protein: 18.5, carbs: 0, fat: 0.7, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferWildCaught: true,
    richInB12: true, richInSelenium: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Shrimp',
    category: 'SEAFOOD',
    aipPhase: 'ELIMINATION',
    calories: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, netCarbs: 0.2,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferWildCaught: true,
    richInB12: true, richInSelenium: true, richInIodine: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Sardines (Canned)',
    category: 'SEAFOOD',
    aipPhase: 'ELIMINATION',
    calories: 208, protein: 25, carbs: 0, fat: 11.5, fiber: 0, netCarbs: 0,
    tyramineLevel: 'HIGH', histamineLevel: 'HIGH',
    preferWildCaught: true,
    richInB12: true, richInOmega3: true, richInCalcium: true, richInVitaminD: true,
    servingSize: '3.75 oz can', servingSizeGrams: 106,
  },
  {
    name: 'Tuna (Fresh)',
    category: 'SEAFOOD',
    aipPhase: 'ELIMINATION',
    calories: 109, protein: 24, carbs: 0, fat: 0.5, fiber: 0, netCarbs: 0,
    tyramineLevel: 'MODERATE', histamineLevel: 'HIGH',
    preferWildCaught: true,
    richInB12: true, richInSelenium: true, richInOmega3: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Scallops',
    category: 'SEAFOOD',
    aipPhase: 'ELIMINATION',
    calories: 69, protein: 12, carbs: 3.2, fat: 0.5, fiber: 0, netCarbs: 3.2,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferWildCaught: true,
    richInB12: true, richInSelenium: true, richInZinc: true,
    servingSize: '4 oz', servingSizeGrams: 113,
  },
  {
    name: 'Oysters',
    category: 'SEAFOOD',
    aipPhase: 'ELIMINATION',
    calories: 68, protein: 7, carbs: 3.9, fat: 2.5, fiber: 0, netCarbs: 3.9,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferWildCaught: true,
    richInB12: true, richInZinc: true, richInIron: true, richInSelenium: true, richInIodine: true,
    servingSize: '6 medium', servingSizeGrams: 84,
  },

  // ── VEGETABLES ──
  {
    name: 'Sweet Potato',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 86, protein: 1.6, carbs: 20, fat: 0.1, fiber: 3, netCarbs: 17,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true,
    richInMagnesium: true,
    servingSize: '1 medium', servingSizeGrams: 130,
  },
  {
    name: 'Cauliflower',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 25, protein: 1.9, carbs: 5, fat: 0.3, fiber: 2, netCarbs: 3,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInFolate: true,
    servingSize: '1 cup', servingSizeGrams: 107,
  },
  {
    name: 'Broccoli',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 34, protein: 2.8, carbs: 7, fat: 0.4, fiber: 2.6, netCarbs: 4.4,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true,
    richInFolate: true,
    servingSize: '1 cup chopped', servingSizeGrams: 91,
  },
  {
    name: 'Zucchini',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1, netCarbs: 2.1,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 medium', servingSizeGrams: 196,
  },
  {
    name: 'Spinach',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, netCarbs: 1.4,
    tyramineLevel: 'LOW', histamineLevel: 'MODERATE',
    preferOrganic: true,
    richInIron: true, richInFolate: true, richInMagnesium: true,
    servingSize: '2 cups raw', servingSizeGrams: 60,
  },
  {
    name: 'Kale',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 35, protein: 2.9, carbs: 4.4, fat: 1.5, fiber: 4.1, netCarbs: 0.3,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true,
    richInCalcium: true, richInIron: true, richInFolate: true,
    servingSize: '1 cup chopped', servingSizeGrams: 67,
  },
  {
    name: 'Butternut Squash',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 45, protein: 1, carbs: 12, fat: 0.1, fiber: 2, netCarbs: 10,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 cup cubed', servingSizeGrams: 205,
  },
  {
    name: 'Asparagus',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 20, protein: 2.2, carbs: 3.9, fat: 0.1, fiber: 2.1, netCarbs: 1.8,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInFolate: true,
    servingSize: '5 spears', servingSizeGrams: 93,
  },
  {
    name: 'Carrots',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, netCarbs: 7.2,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 medium', servingSizeGrams: 61,
  },
  {
    name: 'Beets',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 43, protein: 1.6, carbs: 10, fat: 0.2, fiber: 2.8, netCarbs: 7.2,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInFolate: true,
    servingSize: '1 medium', servingSizeGrams: 82,
  },
  {
    name: 'Cucumber',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, netCarbs: 3.1,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1/2 medium', servingSizeGrams: 150,
  },
  {
    name: 'Celery',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 14, protein: 0.7, carbs: 3, fat: 0.2, fiber: 1.6, netCarbs: 1.4,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '2 stalks', servingSizeGrams: 80,
  },
  {
    name: 'Onion',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7, netCarbs: 7.6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 medium', servingSizeGrams: 110,
  },
  {
    name: 'Garlic',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 149, protein: 6.4, carbs: 33, fat: 0.5, fiber: 2.1, netCarbs: 30.9,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '3 cloves', servingSizeGrams: 9,
  },
  {
    name: 'Mushrooms (Button)',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, netCarbs: 2.3,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInSelenium: true, richInB12: true,
    servingSize: '1 cup sliced', servingSizeGrams: 70,
  },
  {
    name: 'Cabbage (Green)',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 25, protein: 1.3, carbs: 5.8, fat: 0.1, fiber: 2.5, netCarbs: 3.3,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInFolate: true,
    servingSize: '1 cup shredded', servingSizeGrams: 89,
  },
  {
    name: 'Brussels Sprouts',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 43, protein: 3.4, carbs: 9, fat: 0.3, fiber: 3.8, netCarbs: 5.2,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInFolate: true,
    servingSize: '1 cup', servingSizeGrams: 88,
  },
  {
    name: 'Artichoke',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 47, protein: 3.3, carbs: 11, fat: 0.2, fiber: 5.4, netCarbs: 5.6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInFolate: true, richInMagnesium: true,
    servingSize: '1 medium', servingSizeGrams: 128,
  },
  {
    name: 'Lettuce (Romaine)',
    category: 'VEGETABLE',
    aipPhase: 'ELIMINATION',
    calories: 17, protein: 1.2, carbs: 3.3, fat: 0.3, fiber: 2.1, netCarbs: 1.2,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInFolate: true,
    servingSize: '2 cups', servingSizeGrams: 94,
  },

  // ── VEGETABLES: NIGHTSHADES (AVOID in elimination) ──
  {
    name: 'Tomatoes',
    category: 'VEGETABLE',
    aipPhase: 'AVOID',
    calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, netCarbs: 2.7,
    tyramineLevel: 'MODERATE', histamineLevel: 'HIGH',
    whyRestricted: 'Nightshade family. Contains solanine and lectins that can increase intestinal permeability and trigger immune responses.',
    reintroStage: 4,
    reintroNotes: 'One of the last nightshades to reintroduce. Start with well-cooked, peeled, and seeded tomato sauce (1 tsp).',
    servingSize: '1 medium', servingSizeGrams: 123,
  },
  {
    name: 'Bell Peppers',
    category: 'VEGETABLE',
    aipPhase: 'AVOID',
    calories: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, netCarbs: 3.9,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    whyRestricted: 'Nightshade family. Contains capsaicin and solanine compounds that may trigger immune response.',
    reintroStage: 4,
    reintroNotes: 'Start with a small piece of well-cooked sweet bell pepper. Avoid hot peppers longer.',
    servingSize: '1 medium', servingSizeGrams: 119,
  },
  {
    name: 'White Potatoes',
    category: 'VEGETABLE',
    aipPhase: 'AVOID',
    calories: 77, protein: 2, carbs: 17, fat: 0.1, fiber: 2.2, netCarbs: 14.8,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    whyRestricted: 'Nightshade family. Contains glycoalkaloids (solanine) concentrated in the skin. Sweet potatoes are a safe alternative.',
    reintroStage: 3,
    reintroNotes: 'Reintroduce peeled, well-cooked white potato. Start with 1-2 tbsp mashed.',
    servingSize: '1 medium', servingSizeGrams: 150,
  },
  {
    name: 'Eggplant',
    category: 'VEGETABLE',
    aipPhase: 'AVOID',
    calories: 25, protein: 1, carbs: 6, fat: 0.2, fiber: 3, netCarbs: 3,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    whyRestricted: 'Nightshade family. Contains solanine and nicotine alkaloids.',
    reintroStage: 4,
    reintroNotes: 'Reintroduce well-cooked eggplant. Start with 1-2 tablespoons.',
    servingSize: '1 cup cubed', servingSizeGrams: 82,
  },

  // ── FRUIT ──
  {
    name: 'Apple',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, netCarbs: 11.6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true,
    servingSize: '1 medium', servingSizeGrams: 182,
  },
  {
    name: 'Banana',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, netCarbs: 20.4,
    tyramineLevel: 'MODERATE', histamineLevel: 'LOW',
    richInMagnesium: true,
    servingSize: '1 medium', servingSizeGrams: 118,
  },
  {
    name: 'Blueberries',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 57, protein: 0.7, carbs: 14, fat: 0.3, fiber: 2.4, netCarbs: 11.6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true,
    servingSize: '1 cup', servingSizeGrams: 148,
  },
  {
    name: 'Strawberries',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2, netCarbs: 5.7,
    tyramineLevel: 'LOW', histamineLevel: 'MODERATE',
    preferOrganic: true,
    richInFolate: true,
    servingSize: '1 cup', servingSizeGrams: 152,
  },
  {
    name: 'Avocado',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 160, protein: 2, carbs: 8.5, fat: 15, fiber: 6.7, netCarbs: 1.8,
    tyramineLevel: 'MODERATE', histamineLevel: 'MODERATE',
    richInMagnesium: true, richInFolate: true,
    servingSize: '1/2 medium', servingSizeGrams: 68,
  },
  {
    name: 'Lemon',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 29, protein: 1.1, carbs: 9.3, fat: 0.3, fiber: 2.8, netCarbs: 6.5,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 medium', servingSizeGrams: 58,
  },
  {
    name: 'Lime',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 30, protein: 0.7, carbs: 11, fat: 0.2, fiber: 2.8, netCarbs: 8.2,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 medium', servingSizeGrams: 67,
  },
  {
    name: 'Mango',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, netCarbs: 13.4,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInFolate: true,
    servingSize: '1 cup sliced', servingSizeGrams: 165,
  },
  {
    name: 'Pineapple',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 50, protein: 0.5, carbs: 13, fat: 0.1, fiber: 1.4, netCarbs: 11.6,
    tyramineLevel: 'LOW', histamineLevel: 'MODERATE',
    servingSize: '1 cup chunks', servingSizeGrams: 165,
  },
  {
    name: 'Coconut (Fresh)',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 354, protein: 3.3, carbs: 15, fat: 33, fiber: 9, netCarbs: 6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInMagnesium: true, richInIron: true,
    servingSize: '1/4 cup shredded', servingSizeGrams: 20,
  },
  {
    name: 'Dates (Medjool)',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 277, protein: 1.8, carbs: 75, fat: 0.2, fiber: 6.7, netCarbs: 68.3,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInMagnesium: true,
    servingSize: '2 dates', servingSizeGrams: 48,
  },
  {
    name: 'Plantain',
    category: 'FRUIT',
    aipPhase: 'ELIMINATION',
    calories: 122, protein: 1.3, carbs: 32, fat: 0.4, fiber: 2.3, netCarbs: 29.7,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInMagnesium: true,
    servingSize: '1 medium', servingSizeGrams: 179,
  },

  // ── FATS & OILS ──
  {
    name: 'Coconut Oil',
    category: 'FAT_OIL',
    aipPhase: 'ELIMINATION',
    calories: 862, protein: 0, carbs: 0, fat: 100, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true,
    servingSize: '1 tbsp', servingSizeGrams: 14,
  },
  {
    name: 'Olive Oil (Extra Virgin)',
    category: 'FAT_OIL',
    aipPhase: 'ELIMINATION',
    calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true,
    servingSize: '1 tbsp', servingSizeGrams: 14,
  },
  {
    name: 'Avocado Oil',
    category: 'FAT_OIL',
    aipPhase: 'ELIMINATION',
    calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 tbsp', servingSizeGrams: 14,
  },
  {
    name: 'Lard (Pasture-Raised)',
    category: 'FAT_OIL',
    aipPhase: 'ELIMINATION',
    calories: 902, protein: 0, carbs: 0, fat: 100, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferPasture: true,
    servingSize: '1 tbsp', servingSizeGrams: 13,
  },
  {
    name: 'Tallow (Beef)',
    category: 'FAT_OIL',
    aipPhase: 'ELIMINATION',
    calories: 902, protein: 0, carbs: 0, fat: 100, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferGrassFed: true,
    servingSize: '1 tbsp', servingSizeGrams: 13,
  },
  {
    name: 'Coconut Cream',
    category: 'FAT_OIL',
    aipPhase: 'ELIMINATION',
    calories: 330, protein: 3.6, carbs: 6.6, fat: 35, fiber: 0, netCarbs: 6.6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1/4 cup', servingSizeGrams: 60,
  },
  {
    name: 'Coconut Milk (Full Fat)',
    category: 'FAT_OIL',
    aipPhase: 'ELIMINATION',
    calories: 230, protein: 2.3, carbs: 6, fat: 24, fiber: 0, netCarbs: 6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1/2 cup', servingSizeGrams: 120,
  },
  {
    name: 'Coconut Butter',
    category: 'FAT_OIL',
    aipPhase: 'ELIMINATION',
    calories: 620, protein: 6, carbs: 22, fat: 60, fiber: 12, netCarbs: 10,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '2 tbsp', servingSizeGrams: 32,
  },

  // ── HERBS & SPICES ──
  {
    name: 'Turmeric',
    category: 'HERB_SPICE',
    aipPhase: 'ELIMINATION',
    calories: 312, protein: 9.7, carbs: 67, fat: 3.2, fiber: 22.7, netCarbs: 44.3,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 tsp', servingSizeGrams: 3,
  },
  {
    name: 'Ginger',
    category: 'HERB_SPICE',
    aipPhase: 'ELIMINATION',
    calories: 80, protein: 1.8, carbs: 18, fat: 0.8, fiber: 2, netCarbs: 16,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 tsp grated', servingSizeGrams: 2,
  },
  {
    name: 'Cinnamon',
    category: 'HERB_SPICE',
    aipPhase: 'ELIMINATION',
    calories: 247, protein: 4, carbs: 81, fat: 1.2, fiber: 53, netCarbs: 28,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 tsp', servingSizeGrams: 2.6,
  },
  {
    name: 'Sea Salt',
    category: 'HERB_SPICE',
    aipPhase: 'ELIMINATION',
    calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInIodine: true,
    servingSize: '1/4 tsp', servingSizeGrams: 1.5,
  },
  {
    name: 'Basil (Fresh)',
    category: 'HERB_SPICE',
    aipPhase: 'ELIMINATION',
    calories: 23, protein: 3.2, carbs: 2.7, fat: 0.6, fiber: 1.6, netCarbs: 1.1,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '2 tbsp chopped', servingSizeGrams: 5,
  },
  {
    name: 'Oregano (Dried)',
    category: 'HERB_SPICE',
    aipPhase: 'ELIMINATION',
    calories: 265, protein: 9, carbs: 69, fat: 4.3, fiber: 43, netCarbs: 26,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInIron: true, richInCalcium: true,
    servingSize: '1 tsp', servingSizeGrams: 1,
  },
  {
    name: 'Thyme (Fresh)',
    category: 'HERB_SPICE',
    aipPhase: 'ELIMINATION',
    calories: 101, protein: 5.6, carbs: 24, fat: 1.7, fiber: 14, netCarbs: 10,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInIron: true,
    servingSize: '1 tsp', servingSizeGrams: 1,
  },
  {
    name: 'Rosemary (Fresh)',
    category: 'HERB_SPICE',
    aipPhase: 'ELIMINATION',
    calories: 131, protein: 3.3, carbs: 21, fat: 5.9, fiber: 14, netCarbs: 7,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInIron: true, richInCalcium: true,
    servingSize: '1 tsp', servingSizeGrams: 1,
  },
  {
    name: 'Parsley (Fresh)',
    category: 'HERB_SPICE',
    aipPhase: 'ELIMINATION',
    calories: 36, protein: 3, carbs: 6.3, fat: 0.8, fiber: 3.3, netCarbs: 3,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInFolate: true, richInIron: true,
    servingSize: '1/4 cup chopped', servingSizeGrams: 15,
  },

  // ── BROTHS ──
  {
    name: 'Bone Broth (Chicken)',
    category: 'BROTH',
    aipPhase: 'ELIMINATION',
    calories: 35, protein: 6, carbs: 3, fat: 0.5, fiber: 0, netCarbs: 3,
    tyramineLevel: 'LOW', histamineLevel: 'MODERATE',
    preferOrganic: true, preferPasture: true,
    richInCollagen: true,
    servingSize: '1 cup', servingSizeGrams: 240,
  },
  {
    name: 'Bone Broth (Beef)',
    category: 'BROTH',
    aipPhase: 'ELIMINATION',
    calories: 40, protein: 8, carbs: 1, fat: 0.5, fiber: 0, netCarbs: 1,
    tyramineLevel: 'LOW', histamineLevel: 'MODERATE',
    preferGrassFed: true,
    richInCollagen: true,
    servingSize: '1 cup', servingSizeGrams: 240,
  },

  // ── SMOOTHIE INGREDIENTS ──
  {
    name: 'Collagen Peptides',
    category: 'SMOOTHIE_INGREDIENT',
    aipPhase: 'ELIMINATION',
    calories: 35, protein: 9, carbs: 0, fat: 0, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferGrassFed: true,
    richInCollagen: true,
    servingSize: '1 scoop', servingSizeGrams: 10,
  },
  {
    name: 'Coconut Yogurt (Unsweetened)',
    category: 'SMOOTHIE_INGREDIENT',
    aipPhase: 'ELIMINATION',
    calories: 140, protein: 1, carbs: 8, fat: 12, fiber: 0, netCarbs: 8,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1/2 cup', servingSizeGrams: 120,
  },
  {
    name: 'Tigernut Flour',
    category: 'SMOOTHIE_INGREDIENT',
    aipPhase: 'ELIMINATION',
    calories: 450, protein: 5, carbs: 70, fat: 20, fiber: 30, netCarbs: 40,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInMagnesium: true, richInIron: true,
    servingSize: '1/4 cup', servingSizeGrams: 30,
  },
  {
    name: 'Cassava Flour',
    category: 'SMOOTHIE_INGREDIENT',
    aipPhase: 'ELIMINATION',
    calories: 330, protein: 1.4, carbs: 80, fat: 0.6, fiber: 3.7, netCarbs: 76.3,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1/4 cup', servingSizeGrams: 30,
  },
  {
    name: 'Arrowroot Starch',
    category: 'SMOOTHIE_INGREDIENT',
    aipPhase: 'ELIMINATION',
    calories: 357, protein: 0.3, carbs: 88, fat: 0.1, fiber: 3.4, netCarbs: 84.6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 tbsp', servingSizeGrams: 8,
  },

  // ── BEVERAGES ──
  {
    name: 'Green Tea',
    category: 'BEVERAGE',
    aipPhase: 'ELIMINATION',
    calories: 1, protein: 0, carbs: 0, fat: 0, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 cup', servingSizeGrams: 245,
  },
  {
    name: 'Herbal Tea (Chamomile)',
    category: 'BEVERAGE',
    aipPhase: 'ELIMINATION',
    calories: 1, protein: 0, carbs: 0.2, fat: 0, fiber: 0, netCarbs: 0.2,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    servingSize: '1 cup', servingSizeGrams: 245,
  },
  {
    name: 'Coconut Water',
    category: 'BEVERAGE',
    aipPhase: 'ELIMINATION',
    calories: 19, protein: 0.7, carbs: 3.7, fat: 0.2, fiber: 1.1, netCarbs: 2.6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    richInMagnesium: true,
    servingSize: '1 cup', servingSizeGrams: 240,
  },

  // ── REINTRO STAGE 1: Egg yolks, Ghee, Seed-based spices ──
  {
    name: 'Egg Yolks',
    category: 'OTHER',
    aipPhase: 'REINTRO_1',
    calories: 322, protein: 16, carbs: 3.6, fat: 27, fiber: 0, netCarbs: 3.6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferPasture: true, preferOrganic: true,
    richInB12: true, richInCholine: true, richInVitaminD: true,
    whyRestricted: 'Eggs are common immune triggers. Egg yolks are less reactive than whites and are reintroduced first.',
    reintroStage: 1,
    reintroNotes: 'Start with 1 cooked egg yolk only (no white). Wait 72 hours and monitor symptoms.',
    servingSize: '1 yolk', servingSizeGrams: 17,
  },
  {
    name: 'Ghee',
    category: 'FAT_OIL',
    aipPhase: 'REINTRO_1',
    calories: 900, protein: 0, carbs: 0, fat: 100, fiber: 0, netCarbs: 0,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferGrassFed: true, preferOrganic: true,
    whyRestricted: 'Dairy product. Ghee has minimal casein/whey but trace amounts may affect sensitive individuals.',
    reintroStage: 1,
    reintroNotes: 'Start with 1/2 tsp ghee. Ghee is the safest dairy to reintroduce because most proteins are removed.',
    servingSize: '1 tbsp', servingSizeGrams: 14,
  },
  {
    name: 'Black Pepper',
    category: 'HERB_SPICE',
    aipPhase: 'REINTRO_1',
    calories: 251, protein: 10, carbs: 64, fat: 3.3, fiber: 25, netCarbs: 39,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    whyRestricted: 'Seed-based spice. Piperine may affect gut permeability in some individuals.',
    reintroStage: 1,
    reintroNotes: 'Start with a small pinch of black pepper on food. Monitor for 72 hours.',
    servingSize: '1/4 tsp', servingSizeGrams: 0.6,
  },

  // ── REINTRO STAGE 2: Whole eggs, Nuts, Seeds ──
  {
    name: 'Whole Eggs',
    category: 'OTHER',
    aipPhase: 'REINTRO_2',
    calories: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0, netCarbs: 1.1,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferPasture: true, preferOrganic: true,
    richInB12: true, richInCholine: true, richInVitaminD: true, richInSelenium: true,
    whyRestricted: 'Egg whites contain lysozyme and other proteins that can trigger immune response and increase gut permeability.',
    reintroStage: 2,
    reintroNotes: 'After tolerating yolks, try 1 whole cooked egg. Wait 72 hours.',
    servingSize: '1 large', servingSizeGrams: 50,
  },
  {
    name: 'Almonds',
    category: 'OTHER',
    aipPhase: 'REINTRO_2',
    calories: 579, protein: 21, carbs: 22, fat: 50, fiber: 12, netCarbs: 10,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferOrganic: true,
    richInMagnesium: true, richInCalcium: true,
    whyRestricted: 'Tree nut. Contains phytic acid and enzyme inhibitors that can irritate the gut lining.',
    reintroStage: 2,
    reintroNotes: 'Start with 4-5 soaked/dehydrated almonds. Wait 72 hours.',
    servingSize: '1 oz', servingSizeGrams: 28,
  },

  // ── REINTRO STAGE 3: Butter, Rice, Legumes (lentils) ──
  {
    name: 'Butter',
    category: 'FAT_OIL',
    aipPhase: 'REINTRO_3',
    calories: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, netCarbs: 0.1,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferGrassFed: true, preferOrganic: true,
    whyRestricted: 'Dairy product. Contains casein and whey proteins that trigger immune response in sensitive individuals.',
    reintroStage: 3,
    reintroNotes: 'After tolerating ghee, try 1/2 tsp butter. Contains more dairy proteins than ghee.',
    servingSize: '1 tbsp', servingSizeGrams: 14,
  },
  {
    name: 'White Rice',
    category: 'OTHER',
    aipPhase: 'REINTRO_3',
    calories: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, netCarbs: 27.6,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    whyRestricted: 'Grain. While gluten-free, rice contains lectins. White rice is the least problematic grain.',
    reintroStage: 3,
    reintroNotes: 'Start with 2-3 tablespoons of well-cooked white rice. White rice has fewer antinutrients than brown.',
    servingSize: '1/2 cup cooked', servingSizeGrams: 93,
  },

  // ── AVOID (Common allergens) ──
  {
    name: 'Soy / Soy Sauce',
    category: 'OTHER',
    aipPhase: 'AVOID',
    calories: 53, protein: 8, carbs: 5, fat: 0.6, fiber: 0.8, netCarbs: 4.2,
    tyramineLevel: 'HIGH', histamineLevel: 'HIGH',
    whyRestricted: 'Legume. Contains isoflavones (phytoestrogens), lectins, and saponins. Fermented soy is also high in tyramine and histamine.',
    servingSize: '1 tbsp', servingSizeGrams: 15,
  },
  {
    name: 'Peanuts',
    category: 'OTHER',
    aipPhase: 'AVOID',
    calories: 567, protein: 26, carbs: 16, fat: 49, fiber: 8.5, netCarbs: 7.5,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    whyRestricted: 'Legume (not a tree nut). Contains lectins, phytic acid, and aflatoxins. Common allergen.',
    servingSize: '1 oz', servingSizeGrams: 28,
  },
  {
    name: 'Wheat / Gluten',
    category: 'OTHER',
    aipPhase: 'AVOID',
    calories: 340, protein: 13, carbs: 72, fat: 2.5, fiber: 11, netCarbs: 61,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    whyRestricted: 'Grain containing gluten. Gluten increases intestinal permeability (leaky gut) and triggers immune response even in non-celiac individuals.',
    servingSize: '1 slice bread', servingSizeGrams: 30,
  },
  {
    name: 'Corn',
    category: 'OTHER',
    aipPhase: 'AVOID',
    calories: 86, protein: 3.3, carbs: 19, fat: 1.2, fiber: 2.7, netCarbs: 16.3,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    preferNonGMO: true,
    whyRestricted: 'Grain. Contains zein (a prolamin similar to gluten) and lectins. Often GMO and heavily sprayed.',
    servingSize: '1 ear', servingSizeGrams: 90,
  },
  {
    name: 'Cow Milk',
    category: 'OTHER',
    aipPhase: 'AVOID',
    calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, netCarbs: 4.8,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    whyRestricted: 'Dairy. Contains casein and whey proteins that cross-react with gluten and trigger immune responses. Lactose can cause digestive issues.',
    servingSize: '1 cup', servingSizeGrams: 244,
  },
  {
    name: 'Cheese (Aged)',
    category: 'OTHER',
    aipPhase: 'AVOID',
    calories: 403, protein: 25, carbs: 1.3, fat: 33, fiber: 0, netCarbs: 1.3,
    tyramineLevel: 'HIGH', histamineLevel: 'HIGH',
    whyRestricted: 'Dairy product. Aged cheeses are very high in tyramine and histamine, making them a double trigger for sensitive individuals.',
    servingSize: '1 oz', servingSizeGrams: 28,
  },
  {
    name: 'Refined Sugar',
    category: 'OTHER',
    aipPhase: 'AVOID',
    calories: 387, protein: 0, carbs: 100, fat: 0, fiber: 0, netCarbs: 100,
    tyramineLevel: 'LOW', histamineLevel: 'LOW',
    whyRestricted: 'Feeds harmful gut bacteria, promotes inflammation, spikes blood sugar, and disrupts immune function.',
    servingSize: '1 tsp', servingSizeGrams: 4,
  },
  {
    name: 'Alcohol',
    category: 'BEVERAGE',
    aipPhase: 'AVOID',
    calories: 231, protein: 0, carbs: 0, fat: 0, fiber: 0, netCarbs: 0,
    tyramineLevel: 'HIGH', histamineLevel: 'HIGH',
    whyRestricted: 'Increases intestinal permeability (leaky gut), disrupts gut microbiome, impairs immune function, and is high in both tyramine and histamine.',
    servingSize: '5 oz wine', servingSizeGrams: 148,
  },
];

async function main() {
  console.log('Seeding AIP food database...');
  let created = 0;
  let skipped = 0;

  for (const food of foods) {
    const existing = await prisma.aIPFood.findFirst({ where: { name: food.name } });
    if (existing) {
      console.log(`  Skipped (exists): ${food.name}`);
      skipped++;
      continue;
    }

    // Remove any fields not in the Prisma schema (like richInCollagen)
    const { richInCollagen, ...foodData } = food as typeof food & { richInCollagen?: boolean };
    void richInCollagen; // suppress unused warning

    await prisma.aIPFood.create({ data: foodData as any });
    console.log(`  Created: ${food.name}`);
    created++;
  }

  console.log(`\nDone! Created ${created} foods, skipped ${skipped} existing.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
